import type { MinecraftBlockColor } from "./gradient-types";

// Generated from the Java Edition 26.1.2 block catalog and each texture's
// average RGB color. Source catalog: https://palettinator.com/api/blocks
// Source colors: https://palettinator.com/assets/blockTextureColors-3qXc8Nl6.js
// The corresponding textures are stored locally for stable previews.
export const MINECRAFT_BLOCK_COLORS: MinecraftBlockColor[] = [
  {"id":"brain_coral_block","name":"Brain Coral Block","hex":"#cf5b9f","family":"ocean","category":"aquatic","texture":"brain_coral_block.png","common":true},
  {"id":"bubble_coral_block","name":"Bubble Coral Block","hex":"#a51aa2","family":"ocean","category":"aquatic","texture":"bubble_coral_block.png","common":true},
  {"id":"dead_brain_coral_block","name":"Dead Brain Coral Block","hex":"#7c7672","family":"ocean","category":"aquatic","texture":"dead_brain_coral_block.png","common":true},
  {"id":"dead_bubble_coral_block","name":"Dead Bubble Coral Block","hex":"#847c77","family":"ocean","category":"aquatic","texture":"dead_bubble_coral_block.png","common":true},
  {"id":"dead_fire_coral_block","name":"Dead Fire Coral Block","hex":"#847c78","family":"ocean","category":"aquatic","texture":"dead_fire_coral_block.png","common":true},
  {"id":"dead_horn_coral_block","name":"Dead Horn Coral Block","hex":"#867e7a","family":"ocean","category":"aquatic","texture":"dead_horn_coral_block.png","common":true},
  {"id":"dead_tube_coral_block","name":"Dead Tube Coral Block","hex":"#827b78","family":"ocean","category":"aquatic","texture":"dead_tube_coral_block.png","common":true},
  {"id":"fire_coral_block","name":"Fire Coral Block","hex":"#a4232f","family":"ocean","category":"aquatic","texture":"fire_coral_block.png","common":true},
  {"id":"horn_coral_block","name":"Horn Coral Block","hex":"#d8c842","family":"ocean","category":"aquatic","texture":"horn_coral_block.png","common":true},
  {"id":"sponge","name":"Sponge","hex":"#c4c04b","family":"ocean","category":"aquatic","texture":"sponge.png","common":true},
  {"id":"tube_coral_block","name":"Tube Coral Block","hex":"#3157cf","family":"ocean","category":"aquatic","texture":"tube_coral_block.png","common":true},
  {"id":"wet_sponge","name":"Wet Sponge","hex":"#abb546","family":"ocean","category":"aquatic","texture":"wet_sponge.png","common":true},
  {"id":"black_concrete","name":"Black Concrete","hex":"#080a0f","family":"color","category":"concrete","texture":"black_concrete.png","common":true},
  {"id":"black_concrete_powder","name":"Black Concrete Powder","hex":"#191b20","family":"color","category":"concrete","texture":"black_concrete_powder.png","common":true},
  {"id":"blue_concrete","name":"Blue Concrete","hex":"#2d2f8f","family":"color","category":"concrete","texture":"blue_concrete.png","common":true},
  {"id":"blue_concrete_powder","name":"Blue Concrete Powder","hex":"#4649a7","family":"color","category":"concrete","texture":"blue_concrete_powder.png","common":true},
  {"id":"brown_concrete","name":"Brown Concrete","hex":"#603c20","family":"color","category":"concrete","texture":"brown_concrete.png","common":true},
  {"id":"brown_concrete_powder","name":"Brown Concrete Powder","hex":"#7e5536","family":"color","category":"concrete","texture":"brown_concrete_powder.png","common":true},
  {"id":"cyan_concrete","name":"Cyan Concrete","hex":"#157788","family":"color","category":"concrete","texture":"cyan_concrete.png","common":true},
  {"id":"cyan_concrete_powder","name":"Cyan Concrete Powder","hex":"#25949d","family":"color","category":"concrete","texture":"cyan_concrete_powder.png","common":true},
  {"id":"gray_concrete","name":"Gray Concrete","hex":"#373a3e","family":"color","category":"concrete","texture":"gray_concrete.png","common":true},
  {"id":"gray_concrete_powder","name":"Gray Concrete Powder","hex":"#4d5155","family":"color","category":"concrete","texture":"gray_concrete_powder.png","common":true},
  {"id":"green_concrete","name":"Green Concrete","hex":"#495b24","family":"color","category":"concrete","texture":"green_concrete.png","common":true},
  {"id":"green_concrete_powder","name":"Green Concrete Powder","hex":"#61772d","family":"color","category":"concrete","texture":"green_concrete_powder.png","common":true},
  {"id":"light_blue_concrete","name":"Light Blue Concrete","hex":"#2489c7","family":"color","category":"concrete","texture":"light_blue_concrete.png","common":true},
  {"id":"light_blue_concrete_powder","name":"Light Blue Concrete Powder","hex":"#4ab5d5","family":"color","category":"concrete","texture":"light_blue_concrete_powder.png","common":true},
  {"id":"light_gray_concrete","name":"Light Gray Concrete","hex":"#7d7d73","family":"color","category":"concrete","texture":"light_gray_concrete.png","common":true},
  {"id":"light_gray_concrete_powder","name":"Light Gray Concrete Powder","hex":"#9b9b94","family":"color","category":"concrete","texture":"light_gray_concrete_powder.png","common":true},
  {"id":"lime_concrete","name":"Lime Concrete","hex":"#5ea919","family":"color","category":"concrete","texture":"lime_concrete.png","common":true},
  {"id":"lime_concrete_powder","name":"Lime Concrete Powder","hex":"#7dbd2a","family":"color","category":"concrete","texture":"lime_concrete_powder.png","common":true},
  {"id":"magenta_concrete","name":"Magenta Concrete","hex":"#a9309f","family":"color","category":"concrete","texture":"magenta_concrete.png","common":true},
  {"id":"magenta_concrete_powder","name":"Magenta Concrete Powder","hex":"#c154b9","family":"color","category":"concrete","texture":"magenta_concrete_powder.png","common":true},
  {"id":"orange_concrete","name":"Orange Concrete","hex":"#e06101","family":"color","category":"concrete","texture":"orange_concrete.png","common":true},
  {"id":"orange_concrete_powder","name":"Orange Concrete Powder","hex":"#e38420","family":"color","category":"concrete","texture":"orange_concrete_powder.png","common":true},
  {"id":"pink_concrete","name":"Pink Concrete","hex":"#d6658f","family":"color","category":"concrete","texture":"pink_concrete.png","common":true},
  {"id":"pink_concrete_powder","name":"Pink Concrete Powder","hex":"#e599b5","family":"color","category":"concrete","texture":"pink_concrete_powder.png","common":true},
  {"id":"purple_concrete","name":"Purple Concrete","hex":"#64209c","family":"color","category":"concrete","texture":"purple_concrete.png","common":true},
  {"id":"purple_concrete_powder","name":"Purple Concrete Powder","hex":"#8438b2","family":"color","category":"concrete","texture":"purple_concrete_powder.png","common":true},
  {"id":"red_concrete","name":"Red Concrete","hex":"#8e2121","family":"color","category":"concrete","texture":"red_concrete.png","common":true},
  {"id":"red_concrete_powder","name":"Red Concrete Powder","hex":"#a83633","family":"color","category":"concrete","texture":"red_concrete_powder.png","common":true},
  {"id":"white_concrete","name":"White Concrete","hex":"#cfd5d6","family":"color","category":"concrete","texture":"white_concrete.png","common":true},
  {"id":"white_concrete_powder","name":"White Concrete Powder","hex":"#e2e3e4","family":"color","category":"concrete","texture":"white_concrete_powder.png","common":true},
  {"id":"yellow_concrete","name":"Yellow Concrete","hex":"#f1af15","family":"color","category":"concrete","texture":"yellow_concrete.png","common":true},
  {"id":"yellow_concrete_powder","name":"Yellow Concrete Powder","hex":"#e9c737","family":"color","category":"concrete","texture":"yellow_concrete_powder.png","common":true},
  {"id":"chiseled_copper","name":"Chiseled Copper","hex":"#b8654a","family":"metal","category":"copper","texture":"chiseled_copper.png","common":false},
  {"id":"copper_block","name":"Copper Block","hex":"#c06c50","family":"metal","category":"copper","texture":"copper_block.png","common":false},
  {"id":"copper_bulb","name":"Copper Bulb","hex":"#9c5739","family":"metal","category":"copper","texture":"copper_bulb.png","common":false},
  {"id":"copper_grate","name":"Copper Grate","hex":"#c06c4f","family":"metal","category":"copper","texture":"copper_grate.png","common":false},
  {"id":"copper_trapdoor","name":"Copper Trapdoor","hex":"#bf6a50","family":"metal","category":"copper","texture":"copper_trapdoor.png","common":false},
  {"id":"cut_copper","name":"Cut Copper","hex":"#bf6b51","family":"metal","category":"copper","texture":"cut_copper.png","common":false},
  {"id":"cut_copper_slab","name":"Cut Copper Slab","hex":"#bf6b51","family":"metal","category":"copper","texture":"cut_copper.png","common":false},
  {"id":"cut_copper_stairs","name":"Cut Copper Stairs","hex":"#bf6b51","family":"metal","category":"copper","texture":"cut_copper.png","common":false},
  {"id":"exposed_chiseled_copper","name":"Exposed Chiseled Copper","hex":"#9b7765","family":"metal","category":"copper","texture":"exposed_chiseled_copper.png","common":false},
  {"id":"exposed_copper","name":"Exposed Copper","hex":"#a17e68","family":"metal","category":"copper","texture":"exposed_copper.png","common":false},
  {"id":"exposed_copper_bulb","name":"Exposed Copper Bulb","hex":"#876c5a","family":"metal","category":"copper","texture":"exposed_copper_bulb.png","common":false},
  {"id":"exposed_copper_grate","name":"Exposed Copper Grate","hex":"#a27e69","family":"metal","category":"copper","texture":"exposed_copper_grate.png","common":false},
  {"id":"exposed_copper_trapdoor","name":"Exposed Copper Trapdoor","hex":"#a17d69","family":"metal","category":"copper","texture":"exposed_copper_trapdoor.png","common":false},
  {"id":"exposed_cut_copper","name":"Exposed Cut Copper","hex":"#9b7a65","family":"metal","category":"copper","texture":"exposed_cut_copper.png","common":false},
  {"id":"exposed_cut_copper_slab","name":"Exposed Cut Copper Slab","hex":"#9b7a65","family":"metal","category":"copper","texture":"exposed_cut_copper.png","common":false},
  {"id":"exposed_cut_copper_stairs","name":"Exposed Cut Copper Stairs","hex":"#9b7a65","family":"metal","category":"copper","texture":"exposed_cut_copper.png","common":false},
  {"id":"oxidized_chiseled_copper","name":"Oxidized Chiseled Copper","hex":"#54a284","family":"metal","category":"copper","texture":"oxidized_chiseled_copper.png","common":false},
  {"id":"oxidized_copper","name":"Oxidized Copper","hex":"#52a385","family":"metal","category":"copper","texture":"oxidized_copper.png","common":false},
  {"id":"oxidized_copper_bulb","name":"Oxidized Copper Bulb","hex":"#46846d","family":"metal","category":"copper","texture":"oxidized_copper_bulb.png","common":false},
  {"id":"oxidized_copper_grate","name":"Oxidized Copper Grate","hex":"#52a183","family":"metal","category":"copper","texture":"oxidized_copper_grate.png","common":false},
  {"id":"oxidized_copper_trapdoor","name":"Oxidized Copper Trapdoor","hex":"#54a184","family":"metal","category":"copper","texture":"oxidized_copper_trapdoor.png","common":false},
  {"id":"oxidized_cut_copper","name":"Oxidized Cut Copper","hex":"#509a7e","family":"metal","category":"copper","texture":"oxidized_cut_copper.png","common":false},
  {"id":"oxidized_cut_copper_slab","name":"Oxidized Cut Copper Slab","hex":"#509a7e","family":"metal","category":"copper","texture":"oxidized_cut_copper.png","common":false},
  {"id":"oxidized_cut_copper_stairs","name":"Oxidized Cut Copper Stairs","hex":"#509a7e","family":"metal","category":"copper","texture":"oxidized_cut_copper.png","common":false},
  {"id":"raw_copper_block","name":"Raw Copper Block","hex":"#9a6a4f","family":"metal","category":"copper","texture":"raw_copper_block.png","common":false},
  {"id":"waxed_chiseled_copper","name":"Waxed Chiseled Copper","hex":"#b8654a","family":"metal","category":"copper","texture":"chiseled_copper.png","common":false},
  {"id":"waxed_copper_block","name":"Waxed Copper Block","hex":"#c06c50","family":"metal","category":"copper","texture":"copper_block.png","common":false},
  {"id":"waxed_copper_bulb","name":"Waxed Copper Bulb","hex":"#9c5739","family":"metal","category":"copper","texture":"copper_bulb.png","common":false},
  {"id":"waxed_copper_grate","name":"Waxed Copper Grate","hex":"#c06c4f","family":"metal","category":"copper","texture":"copper_grate.png","common":false},
  {"id":"waxed_copper_trapdoor","name":"Waxed Copper Trapdoor","hex":"#bf6a50","family":"metal","category":"copper","texture":"copper_trapdoor.png","common":false},
  {"id":"waxed_cut_copper","name":"Waxed Cut Copper","hex":"#bf6b51","family":"metal","category":"copper","texture":"cut_copper.png","common":false},
  {"id":"waxed_cut_copper_slab","name":"Waxed Cut Copper Slab","hex":"#bf6b51","family":"metal","category":"copper","texture":"cut_copper.png","common":false},
  {"id":"waxed_exposed_chiseled_copper","name":"Waxed Exposed Chiseled Copper","hex":"#9b7765","family":"metal","category":"copper","texture":"exposed_chiseled_copper.png","common":false},
  {"id":"waxed_exposed_copper","name":"Waxed Exposed Copper","hex":"#a17e68","family":"metal","category":"copper","texture":"exposed_copper.png","common":false},
  {"id":"waxed_exposed_copper_bulb","name":"Waxed Exposed Copper Bulb","hex":"#876c5a","family":"metal","category":"copper","texture":"exposed_copper_bulb.png","common":false},
  {"id":"waxed_exposed_copper_grate","name":"Waxed Exposed Copper Grate","hex":"#a27e69","family":"metal","category":"copper","texture":"exposed_copper_grate.png","common":false},
  {"id":"waxed_exposed_copper_trapdoor","name":"Waxed Exposed Copper Trapdoor","hex":"#a17d69","family":"metal","category":"copper","texture":"exposed_copper_trapdoor.png","common":false},
  {"id":"waxed_exposed_cut_copper","name":"Waxed Exposed Cut Copper","hex":"#9b7a65","family":"metal","category":"copper","texture":"exposed_cut_copper.png","common":false},
  {"id":"waxed_exposed_cut_copper_slab","name":"Waxed Exposed Cut Copper Slab","hex":"#9b7a65","family":"metal","category":"copper","texture":"exposed_cut_copper.png","common":false},
  {"id":"waxed_oxidized_chiseled_copper","name":"Waxed Oxidized Chiseled Copper","hex":"#54a284","family":"metal","category":"copper","texture":"oxidized_chiseled_copper.png","common":false},
  {"id":"waxed_oxidized_copper","name":"Waxed Oxidized Copper","hex":"#52a385","family":"metal","category":"copper","texture":"oxidized_copper.png","common":false},
  {"id":"waxed_oxidized_copper_bulb","name":"Waxed Oxidized Copper Bulb","hex":"#46846d","family":"metal","category":"copper","texture":"oxidized_copper_bulb.png","common":false},
  {"id":"waxed_oxidized_copper_grate","name":"Waxed Oxidized Copper Grate","hex":"#52a183","family":"metal","category":"copper","texture":"oxidized_copper_grate.png","common":false},
  {"id":"waxed_oxidized_copper_trapdoor","name":"Waxed Oxidized Copper Trapdoor","hex":"#54a184","family":"metal","category":"copper","texture":"oxidized_copper_trapdoor.png","common":false},
  {"id":"waxed_oxidized_cut_copper","name":"Waxed Oxidized Cut Copper","hex":"#509a7e","family":"metal","category":"copper","texture":"oxidized_cut_copper.png","common":false},
  {"id":"waxed_oxidized_cut_copper_slab","name":"Waxed Oxidized Cut Copper Slab","hex":"#509a7e","family":"metal","category":"copper","texture":"oxidized_cut_copper.png","common":false},
  {"id":"waxed_weathered_chiseled_copper","name":"Waxed Weathered Chiseled Copper","hex":"#69976f","family":"metal","category":"copper","texture":"weathered_chiseled_copper.png","common":false},
  {"id":"waxed_weathered_copper","name":"Waxed Weathered Copper","hex":"#6c996e","family":"metal","category":"copper","texture":"weathered_copper.png","common":false},
  {"id":"waxed_weathered_copper_bulb","name":"Waxed Weathered Copper Bulb","hex":"#5c7f63","family":"metal","category":"copper","texture":"weathered_copper_bulb.png","common":false},
  {"id":"waxed_weathered_copper_grate","name":"Waxed Weathered Copper Grate","hex":"#6a996f","family":"metal","category":"copper","texture":"weathered_copper_grate.png","common":false},
  {"id":"waxed_weathered_copper_trapdoor","name":"Waxed Weathered Copper Trapdoor","hex":"#6d996e","family":"metal","category":"copper","texture":"weathered_copper_trapdoor.png","common":false},
  {"id":"waxed_weathered_cut_copper","name":"Waxed Weathered Cut Copper","hex":"#6d916c","family":"metal","category":"copper","texture":"weathered_cut_copper.png","common":false},
  {"id":"waxed_weathered_cut_copper_slab","name":"Waxed Weathered Cut Copper Slab","hex":"#6d916c","family":"metal","category":"copper","texture":"weathered_cut_copper.png","common":false},
  {"id":"weathered_chiseled_copper","name":"Weathered Chiseled Copper","hex":"#69976f","family":"metal","category":"copper","texture":"weathered_chiseled_copper.png","common":false},
  {"id":"weathered_copper","name":"Weathered Copper","hex":"#6c996e","family":"metal","category":"copper","texture":"weathered_copper.png","common":false},
  {"id":"weathered_copper_bulb","name":"Weathered Copper Bulb","hex":"#5c7f63","family":"metal","category":"copper","texture":"weathered_copper_bulb.png","common":false},
  {"id":"weathered_copper_grate","name":"Weathered Copper Grate","hex":"#6a996f","family":"metal","category":"copper","texture":"weathered_copper_grate.png","common":false},
  {"id":"weathered_copper_trapdoor","name":"Weathered Copper Trapdoor","hex":"#6d996e","family":"metal","category":"copper","texture":"weathered_copper_trapdoor.png","common":false},
  {"id":"weathered_cut_copper","name":"Weathered Cut Copper","hex":"#6d916c","family":"metal","category":"copper","texture":"weathered_cut_copper.png","common":false},
  {"id":"weathered_cut_copper_slab","name":"Weathered Cut Copper Slab","hex":"#6d916c","family":"metal","category":"copper","texture":"weathered_cut_copper.png","common":false},
  {"id":"weathered_cut_copper_stairs","name":"Weathered Cut Copper Stairs","hex":"#6d916c","family":"metal","category":"copper","texture":"weathered_cut_copper.png","common":false},
  {"id":"chiseled_deepslate","name":"Chiseled Deepslate","hex":"#363637","family":"stone","category":"deepslate","texture":"chiseled_deepslate.png","common":true},
  {"id":"cobbled_deepslate","name":"Cobbled Deepslate","hex":"#4d4d51","family":"stone","category":"deepslate","texture":"cobbled_deepslate.png","common":true},
  {"id":"cobbled_deepslate_slab","name":"Cobbled Deepslate Slab","hex":"#4d4d51","family":"stone","category":"deepslate","texture":"cobbled_deepslate.png","common":true},
  {"id":"cobbled_deepslate_stairs","name":"Cobbled Deepslate Stairs","hex":"#4d4d51","family":"stone","category":"deepslate","texture":"cobbled_deepslate.png","common":true},
  {"id":"cracked_deepslate_bricks","name":"Cracked Deepslate Bricks","hex":"#414141","family":"stone","category":"deepslate","texture":"cracked_deepslate_bricks.png","common":true},
  {"id":"cracked_deepslate_tiles","name":"Cracked Deepslate Tiles","hex":"#353535","family":"stone","category":"deepslate","texture":"cracked_deepslate_tiles.png","common":true},
  {"id":"deepslate","name":"Deepslate","hex":"#505053","family":"stone","category":"deepslate","texture":"deepslate.png","common":true},
  {"id":"deepslate_brick_slab","name":"Deepslate Brick Slab","hex":"#474747","family":"stone","category":"deepslate","texture":"deepslate_bricks.png","common":true},
  {"id":"deepslate_brick_stairs","name":"Deepslate Brick Stairs","hex":"#474747","family":"stone","category":"deepslate","texture":"deepslate_bricks.png","common":true},
  {"id":"deepslate_bricks","name":"Deepslate Bricks","hex":"#474747","family":"stone","category":"deepslate","texture":"deepslate_bricks.png","common":true},
  {"id":"deepslate_tile_slab","name":"Deepslate Tile Slab","hex":"#373737","family":"stone","category":"deepslate","texture":"deepslate_tiles.png","common":true},
  {"id":"deepslate_tile_stairs","name":"Deepslate Tile Stairs","hex":"#373737","family":"stone","category":"deepslate","texture":"deepslate_tiles.png","common":true},
  {"id":"deepslate_tiles","name":"Deepslate Tiles","hex":"#373737","family":"stone","category":"deepslate","texture":"deepslate_tiles.png","common":true},
  {"id":"polished_deepslate","name":"Polished Deepslate","hex":"#484949","family":"stone","category":"deepslate","texture":"polished_deepslate.png","common":true},
  {"id":"polished_deepslate_slab","name":"Polished Deepslate Slab","hex":"#484949","family":"stone","category":"deepslate","texture":"polished_deepslate.png","common":true},
  {"id":"polished_deepslate_stairs","name":"Polished Deepslate Stairs","hex":"#484949","family":"stone","category":"deepslate","texture":"polished_deepslate.png","common":true},
  {"id":"reinforced_deepslate","name":"Reinforced Deepslate","hex":"#666d65","family":"stone","category":"deepslate","texture":"reinforced_deepslate_side.png","common":true},
  {"id":"chorus_flower","name":"Chorus Flower","hex":"#977998","family":"stone","category":"end","texture":"chorus_flower.png","common":false},
  {"id":"chorus_plant","name":"Chorus Plant","hex":"#5e395e","family":"stone","category":"end","texture":"chorus_plant.png","common":false},
  {"id":"dragon_egg","name":"Dragon Egg","hex":"#0d0910","family":"stone","category":"end","texture":"dragon_egg.png","common":false},
  {"id":"end_stone","name":"End Stone","hex":"#dcdf9e","family":"stone","category":"end","texture":"end_stone.png","common":false},
  {"id":"end_stone_brick_slab","name":"End Stone Brick Slab","hex":"#dae0a2","family":"stone","category":"end","texture":"end_stone_bricks.png","common":false},
  {"id":"end_stone_brick_stairs","name":"End Stone Brick Stairs","hex":"#dae0a2","family":"stone","category":"end","texture":"end_stone_bricks.png","common":false},
  {"id":"end_stone_bricks","name":"End Stone Bricks","hex":"#dae0a2","family":"stone","category":"end","texture":"end_stone_bricks.png","common":false},
  {"id":"purpur_block","name":"Purpur Block","hex":"#aa7eaa","family":"stone","category":"end","texture":"purpur_block.png","common":false},
  {"id":"purpur_pillar","name":"Purpur Pillar","hex":"#ac82ac","family":"stone","category":"end","texture":"purpur_pillar.png","common":false},
  {"id":"purpur_slab","name":"Purpur Slab","hex":"#aa7eaa","family":"stone","category":"end","texture":"purpur_block.png","common":false},
  {"id":"purpur_stairs","name":"Purpur Stairs","hex":"#aa7eaa","family":"stone","category":"end","texture":"purpur_block.png","common":false},
  {"id":"black_stained_glass","name":"Black Stained Glass","hex":"#191919","family":"color","category":"glass","texture":"black_stained_glass.png","common":true},
  {"id":"blue_stained_glass","name":"Blue Stained Glass","hex":"#334cb2","family":"color","category":"glass","texture":"blue_stained_glass.png","common":true},
  {"id":"brown_stained_glass","name":"Brown Stained Glass","hex":"#664c33","family":"color","category":"glass","texture":"brown_stained_glass.png","common":true},
  {"id":"cyan_stained_glass","name":"Cyan Stained Glass","hex":"#4c7f99","family":"color","category":"glass","texture":"cyan_stained_glass.png","common":true},
  {"id":"glass","name":"Glass","hex":"#b0d6db","family":"color","category":"glass","texture":"glass.png","common":true},
  {"id":"gray_stained_glass","name":"Gray Stained Glass","hex":"#4c4c4c","family":"color","category":"glass","texture":"gray_stained_glass.png","common":true},
  {"id":"green_stained_glass","name":"Green Stained Glass","hex":"#667f33","family":"color","category":"glass","texture":"green_stained_glass.png","common":true},
  {"id":"light_blue_stained_glass","name":"Light Blue Stained Glass","hex":"#6699d8","family":"color","category":"glass","texture":"light_blue_stained_glass.png","common":true},
  {"id":"light_gray_stained_glass","name":"Light Gray Stained Glass","hex":"#999999","family":"color","category":"glass","texture":"light_gray_stained_glass.png","common":true},
  {"id":"lime_stained_glass","name":"Lime Stained Glass","hex":"#7fcc19","family":"color","category":"glass","texture":"lime_stained_glass.png","common":true},
  {"id":"magenta_stained_glass","name":"Magenta Stained Glass","hex":"#b24cd8","family":"color","category":"glass","texture":"magenta_stained_glass.png","common":true},
  {"id":"orange_stained_glass","name":"Orange Stained Glass","hex":"#d87f33","family":"color","category":"glass","texture":"orange_stained_glass.png","common":true},
  {"id":"pink_stained_glass","name":"Pink Stained Glass","hex":"#f27fa5","family":"color","category":"glass","texture":"pink_stained_glass.png","common":true},
  {"id":"purple_stained_glass","name":"Purple Stained Glass","hex":"#7f3fb2","family":"color","category":"glass","texture":"purple_stained_glass.png","common":true},
  {"id":"red_stained_glass","name":"Red Stained Glass","hex":"#993333","family":"color","category":"glass","texture":"red_stained_glass.png","common":true},
  {"id":"tinted_glass","name":"Tinted Glass","hex":"#2f2234","family":"color","category":"glass","texture":"tinted_glass.png","common":true},
  {"id":"white_stained_glass","name":"White Stained Glass","hex":"#ffffff","family":"color","category":"glass","texture":"white_stained_glass.png","common":true},
  {"id":"yellow_stained_glass","name":"Yellow Stained Glass","hex":"#e5e533","family":"color","category":"glass","texture":"yellow_stained_glass.png","common":true},
  {"id":"amethyst_block","name":"Amethyst Block","hex":"#8662bf","family":"metal","category":"mineral","texture":"amethyst_block.png","common":false},
  {"id":"anvil","name":"Anvil","hex":"#454545","family":"metal","category":"mineral","texture":"anvil.png","common":false},
  {"id":"budding_amethyst","name":"Budding Amethyst","hex":"#8460bb","family":"metal","category":"mineral","texture":"budding_amethyst.png","common":false},
  {"id":"coal_block","name":"Coal Block","hex":"#101010","family":"metal","category":"mineral","texture":"coal_block.png","common":false},
  {"id":"coal_ore","name":"Coal Ore","hex":"#6a6a69","family":"metal","category":"mineral","texture":"coal_ore.png","common":false},
  {"id":"copper_ore","name":"Copper Ore","hex":"#7d7e78","family":"metal","category":"mineral","texture":"copper_ore.png","common":false},
  {"id":"deepslate_coal_ore","name":"Deepslate Coal Ore","hex":"#4a4a4c","family":"metal","category":"mineral","texture":"deepslate_coal_ore.png","common":false},
  {"id":"deepslate_copper_ore","name":"Deepslate Copper Ore","hex":"#5c5d59","family":"metal","category":"mineral","texture":"deepslate_copper_ore.png","common":false},
  {"id":"deepslate_diamond_ore","name":"Deepslate Diamond Ore","hex":"#536a6b","family":"metal","category":"mineral","texture":"deepslate_diamond_ore.png","common":false},
  {"id":"deepslate_emerald_ore","name":"Deepslate Emerald Ore","hex":"#4e6858","family":"metal","category":"mineral","texture":"deepslate_emerald_ore.png","common":false},
  {"id":"deepslate_gold_ore","name":"Deepslate Gold Ore","hex":"#73674e","family":"metal","category":"mineral","texture":"deepslate_gold_ore.png","common":false},
  {"id":"deepslate_iron_ore","name":"Deepslate Iron Ore","hex":"#6b645f","family":"metal","category":"mineral","texture":"deepslate_iron_ore.png","common":false},
  {"id":"deepslate_lapis_ore","name":"Deepslate Lapis Ore","hex":"#505b73","family":"metal","category":"mineral","texture":"deepslate_lapis_ore.png","common":false},
  {"id":"deepslate_redstone_ore","name":"Deepslate Redstone Ore","hex":"#69494b","family":"metal","category":"mineral","texture":"deepslate_redstone_ore.png","common":false},
  {"id":"diamond_block","name":"Diamond Block","hex":"#62ede4","family":"metal","category":"mineral","texture":"diamond_block.png","common":false},
  {"id":"diamond_ore","name":"Diamond Ore","hex":"#798d8d","family":"metal","category":"mineral","texture":"diamond_ore.png","common":false},
  {"id":"emerald_block","name":"Emerald Block","hex":"#2acb58","family":"metal","category":"mineral","texture":"emerald_block.png","common":false},
  {"id":"emerald_ore","name":"Emerald Ore","hex":"#6c8874","family":"metal","category":"mineral","texture":"emerald_ore.png","common":false},
  {"id":"gold_block","name":"Gold Block","hex":"#f6d03e","family":"metal","category":"mineral","texture":"gold_block.png","common":false},
  {"id":"gold_ore","name":"Gold Ore","hex":"#91866b","family":"metal","category":"mineral","texture":"gold_ore.png","common":false},
  {"id":"heavy_core","name":"Heavy Core","hex":"#52565e","family":"metal","category":"mineral","texture":"heavy_core.png","common":false},
  {"id":"iron_block","name":"Iron Block","hex":"#dcdcdc","family":"metal","category":"mineral","texture":"iron_block.png","common":false},
  {"id":"iron_ore","name":"Iron Ore","hex":"#88817b","family":"metal","category":"mineral","texture":"iron_ore.png","common":false},
  {"id":"lapis_block","name":"Lapis Block","hex":"#1f438c","family":"metal","category":"mineral","texture":"lapis_block.png","common":false},
  {"id":"lapis_ore","name":"Lapis Ore","hex":"#6b768d","family":"metal","category":"mineral","texture":"lapis_ore.png","common":false},
  {"id":"nether_gold_ore","name":"Nether Gold Ore","hex":"#73372a","family":"metal","category":"mineral","texture":"nether_gold_ore.png","common":false},
  {"id":"nether_quartz_ore","name":"Nether Quartz Ore","hex":"#76423e","family":"metal","category":"mineral","texture":"nether_quartz_ore.png","common":false},
  {"id":"raw_gold_block","name":"Raw Gold Block","hex":"#dea92f","family":"metal","category":"mineral","texture":"raw_gold_block.png","common":false},
  {"id":"raw_iron_block","name":"Raw Iron Block","hex":"#a6886b","family":"metal","category":"mineral","texture":"raw_iron_block.png","common":false},
  {"id":"redstone_block","name":"Redstone Block","hex":"#b01905","family":"metal","category":"mineral","texture":"redstone_block.png","common":false},
  {"id":"redstone_ore","name":"Redstone Ore","hex":"#8c6e6e","family":"metal","category":"mineral","texture":"redstone_ore.png","common":false},
  {"id":"barrel","name":"Barrel","hex":"#6c5132","family":"earth","category":"misc","texture":"barrel_side.png","common":true},
  {"id":"beacon","name":"Beacon","hex":"#76ddd7","family":"earth","category":"misc","texture":"beacon.png","common":false},
  {"id":"bee_nest","name":"Bee Nest","hex":"#b78e4c","family":"earth","category":"misc","texture":"bee_nest_front.png","common":true},
  {"id":"beehive","name":"Beehive","hex":"#9f804e","family":"earth","category":"misc","texture":"beehive_front.png","common":true},
  {"id":"blast_furnace","name":"Blast Furnace","hex":"#6c6c6b","family":"earth","category":"misc","texture":"blast_furnace_front.png","common":true},
  {"id":"blue_ice","name":"Blue Ice","hex":"#74a8fd","family":"earth","category":"misc","texture":"blue_ice.png","common":true},
  {"id":"bone_block","name":"Bone Block","hex":"#e5e2d0","family":"earth","category":"misc","texture":"bone_block_side.png","common":true},
  {"id":"bookshelf","name":"Bookshelf","hex":"#755f3c","family":"wood","category":"misc","texture":"bookshelf.png","common":true},
  {"id":"brick_slab","name":"Brick Slab","hex":"#976253","family":"stone","category":"misc","texture":"bricks.png","common":true},
  {"id":"brick_stairs","name":"Brick Stairs","hex":"#976253","family":"stone","category":"misc","texture":"bricks.png","common":true},
  {"id":"bricks","name":"Bricks","hex":"#976253","family":"stone","category":"misc","texture":"bricks.png","common":true},
  {"id":"cartography_table","name":"Cartography Table","hex":"#675743","family":"earth","category":"misc","texture":"cartography_table_top.png","common":true},
  {"id":"carved_pumpkin","name":"Carved Pumpkin","hex":"#965411","family":"earth","category":"misc","texture":"carved_pumpkin.png","common":true},
  {"id":"cauldron","name":"Cauldron","hex":"#4a494b","family":"earth","category":"misc","texture":"cauldron_side.png","common":true},
  {"id":"chiseled_bookshelf","name":"Chiseled Bookshelf","hex":"#b29159","family":"wood","category":"misc","texture":"chiseled_bookshelf_top.png","common":true},
  {"id":"chiseled_quartz_block","name":"Chiseled Quartz Block","hex":"#e8e3da","family":"stone","category":"misc","texture":"chiseled_quartz_block.png","common":true},
  {"id":"chiseled_resin_bricks","name":"Chiseled Resin Bricks","hex":"#c95419","family":"stone","category":"misc","texture":"chiseled_resin_bricks.png","common":true},
  {"id":"composter","name":"Composter","hex":"#704620","family":"earth","category":"misc","texture":"composter_side.png","common":true},
  {"id":"crafting_table","name":"Crafting Table","hex":"#816a46","family":"earth","category":"misc","texture":"crafting_table_front.png","common":true},
  {"id":"creaking_heart","name":"Creaking Heart","hex":"#52443f","family":"earth","category":"misc","texture":"creaking_heart.png","common":true},
  {"id":"crying_obsidian","name":"Crying Obsidian","hex":"#210a3c","family":"stone","category":"misc","texture":"crying_obsidian.png","common":true},
  {"id":"dispenser","name":"Dispenser","hex":"#7a7a7a","family":"earth","category":"misc","texture":"dispenser_front.png","common":true},
  {"id":"dried_kelp_block","name":"Dried Kelp Block","hex":"#26311e","family":"ocean","category":"misc","texture":"dried_kelp_side.png","common":true},
  {"id":"dropper","name":"Dropper","hex":"#7a7a7a","family":"earth","category":"misc","texture":"dropper_front.png","common":true},
  {"id":"fletching_table","name":"Fletching Table","hex":"#ad9b6f","family":"earth","category":"misc","texture":"fletching_table_front.png","common":true},
  {"id":"furnace","name":"Furnace","hex":"#5c5b5b","family":"earth","category":"misc","texture":"furnace_front.png","common":true},
  {"id":"hay_block","name":"Hay Block","hex":"#a68826","family":"earth","category":"misc","texture":"hay_block_side.png","common":true},
  {"id":"honey_block","name":"Honey Block","hex":"#fbbc3a","family":"earth","category":"misc","texture":"honey_block_side.png","common":true},
  {"id":"honeycomb_block","name":"Honeycomb Block","hex":"#e5941e","family":"earth","category":"misc","texture":"honeycomb_block.png","common":true},
  {"id":"ice","name":"Ice","hex":"#92b8fe","family":"earth","category":"misc","texture":"ice.png","common":true},
  {"id":"jack_o_lantern","name":"Jack O Lantern","hex":"#d79835","family":"earth","category":"misc","texture":"jack_o_lantern.png","common":true},
  {"id":"jukebox","name":"Jukebox","hex":"#5e402f","family":"earth","category":"misc","texture":"jukebox_top.png","common":true},
  {"id":"lectern","name":"Lectern","hex":"#826538","family":"earth","category":"misc","texture":"lectern_front.png","common":true},
  {"id":"lodestone","name":"Lodestone","hex":"#939599","family":"stone","category":"misc","texture":"lodestone_top.png","common":true},
  {"id":"loom","name":"Loom","hex":"#947752","family":"earth","category":"misc","texture":"loom_front.png","common":true},
  {"id":"melon","name":"Melon","hex":"#72921e","family":"earth","category":"misc","texture":"melon_side.png","common":true},
  {"id":"note_block","name":"Note Block","hex":"#593b29","family":"earth","category":"misc","texture":"note_block.png","common":true},
  {"id":"observer","name":"Observer","hex":"#686767","family":"earth","category":"misc","texture":"observer_front.png","common":true},
  {"id":"obsidian","name":"Obsidian","hex":"#0f0b19","family":"stone","category":"misc","texture":"obsidian.png","common":true},
  {"id":"ochre_froglight","name":"Ochre Froglight","hex":"#f5e9b6","family":"color","category":"misc","texture":"ochre_froglight_side.png","common":true},
  {"id":"packed_ice","name":"Packed Ice","hex":"#8eb4fa","family":"earth","category":"misc","texture":"packed_ice.png","common":true},
  {"id":"pearlescent_froglight","name":"Pearlescent Froglight","hex":"#ece1e5","family":"color","category":"misc","texture":"pearlescent_froglight_side.png","common":true},
  {"id":"powder_snow","name":"Powder Snow","hex":"#f8fdfd","family":"earth","category":"misc","texture":"powder_snow.png","common":true},
  {"id":"pumpkin","name":"Pumpkin","hex":"#c47318","family":"earth","category":"misc","texture":"pumpkin_side.png","common":true},
  {"id":"quartz_block","name":"Quartz Block","hex":"#ece6df","family":"stone","category":"misc","texture":"quartz_block_side.png","common":true},
  {"id":"quartz_bricks","name":"Quartz Bricks","hex":"#ebe5de","family":"stone","category":"misc","texture":"quartz_bricks.png","common":true},
  {"id":"quartz_pillar","name":"Quartz Pillar","hex":"#ece7e0","family":"stone","category":"misc","texture":"quartz_pillar.png","common":true},
  {"id":"quartz_slab","name":"Quartz Slab","hex":"#ece6df","family":"stone","category":"misc","texture":"quartz_block_side.png","common":true},
  {"id":"quartz_stairs","name":"Quartz Stairs","hex":"#ece6df","family":"stone","category":"misc","texture":"quartz_block_side.png","common":true},
  {"id":"redstone_lamp","name":"Redstone Lamp","hex":"#5f371e","family":"metal","category":"misc","texture":"redstone_lamp.png","common":true},
  {"id":"resin_block","name":"Resin Block","hex":"#d96319","family":"earth","category":"misc","texture":"resin_block.png","common":true},
  {"id":"resin_brick_slab","name":"Resin Brick Slab","hex":"#ce5918","family":"stone","category":"misc","texture":"resin_bricks.png","common":true},
  {"id":"resin_brick_stairs","name":"Resin Brick Stairs","hex":"#ce5918","family":"stone","category":"misc","texture":"resin_bricks.png","common":true},
  {"id":"resin_bricks","name":"Resin Bricks","hex":"#ce5918","family":"stone","category":"misc","texture":"resin_bricks.png","common":true},
  {"id":"respawn_anchor","name":"Respawn Anchor","hex":"#28183f","family":"earth","category":"misc","texture":"respawn_anchor_side0.png","common":true},
  {"id":"slime_block","name":"Slime Block","hex":"#70c05c","family":"earth","category":"misc","texture":"slime_block.png","common":true},
  {"id":"smithing_table","name":"Smithing Table","hex":"#392527","family":"earth","category":"misc","texture":"smithing_table_front.png","common":true},
  {"id":"smoker","name":"Smoker","hex":"#584b3a","family":"earth","category":"misc","texture":"smoker_front.png","common":true},
  {"id":"snow","name":"Snow","hex":"#f9fefe","family":"earth","category":"misc","texture":"snow.png","common":true},
  {"id":"spawner","name":"Spawner","hex":"#242e3f","family":"earth","category":"misc","texture":"spawner.png","common":false},
  {"id":"target","name":"Target","hex":"#e5b0a8","family":"earth","category":"misc","texture":"target_side.png","common":true},
  {"id":"tnt","name":"Tnt","hex":"#b65854","family":"earth","category":"misc","texture":"tnt_side.png","common":true},
  {"id":"verdant_froglight","name":"Verdant Froglight","hex":"#d3ebd0","family":"color","category":"misc","texture":"verdant_froglight_side.png","common":true},
  {"id":"acacia_leaves","name":"Acacia Leaves","hex":"#45631b","family":"earth","category":"nature","texture":"acacia_leaves.png","common":true},
  {"id":"azalea_leaves","name":"Azalea Leaves","hex":"#5a732c","family":"earth","category":"nature","texture":"azalea_leaves.png","common":true},
  {"id":"birch_leaves","name":"Birch Leaves","hex":"#41542b","family":"earth","category":"nature","texture":"birch_leaves.png","common":true},
  {"id":"brown_mushroom_block","name":"Brown Mushroom Block","hex":"#957051","family":"earth","category":"nature","texture":"brown_mushroom_block.png","common":true},
  {"id":"cherry_leaves","name":"Cherry Leaves","hex":"#e5adc2","family":"earth","category":"nature","texture":"cherry_leaves.png","common":true},
  {"id":"clay","name":"Clay","hex":"#a1a6b3","family":"earth","category":"nature","texture":"clay.png","common":true},
  {"id":"coarse_dirt","name":"Coarse Dirt","hex":"#77563b","family":"earth","category":"nature","texture":"coarse_dirt.png","common":true},
  {"id":"dark_oak_leaves","name":"Dark Oak Leaves","hex":"#46651b","family":"earth","category":"nature","texture":"dark_oak_leaves.png","common":true},
  {"id":"dirt","name":"Dirt","hex":"#866043","family":"earth","category":"nature","texture":"dirt.png","common":true},
  {"id":"dirt_path","name":"Dirt Path","hex":"#947a41","family":"earth","category":"nature","texture":"dirt_path_top.png","common":true},
  {"id":"farmland","name":"Farmland","hex":"#8f6747","family":"earth","category":"nature","texture":"farmland.png","common":true},
  {"id":"flowering_azalea_leaves","name":"Flowering Azalea Leaves","hex":"#646f3d","family":"earth","category":"nature","texture":"flowering_azalea_leaves.png","common":true},
  {"id":"grass_block","name":"Grass Block","hex":"#7f6b42","family":"earth","category":"nature","texture":"grass_block_side.png","common":true},
  {"id":"gravel","name":"Gravel","hex":"#847f7f","family":"earth","category":"nature","texture":"gravel.png","common":true},
  {"id":"jungle_leaves","name":"Jungle Leaves","hex":"#49671a","family":"earth","category":"nature","texture":"jungle_leaves.png","common":true},
  {"id":"mangrove_leaves","name":"Mangrove Leaves","hex":"#3c5617","family":"earth","category":"nature","texture":"mangrove_leaves.png","common":true},
  {"id":"mangrove_roots","name":"Mangrove Roots","hex":"#4b3c26","family":"earth","category":"nature","texture":"mangrove_roots_side.png","common":true},
  {"id":"moss_block","name":"Moss Block","hex":"#596e2d","family":"earth","category":"nature","texture":"moss_block.png","common":true},
  {"id":"moss_carpet","name":"Moss Carpet","hex":"#596e2d","family":"earth","category":"nature","texture":"moss_block.png","common":true},
  {"id":"mud","name":"Mud","hex":"#3c393d","family":"earth","category":"nature","texture":"mud.png","common":true},
  {"id":"mud_brick_slab","name":"Mud Brick Slab","hex":"#89684f","family":"earth","category":"nature","texture":"mud_bricks.png","common":true},
  {"id":"mud_brick_stairs","name":"Mud Brick Stairs","hex":"#89684f","family":"earth","category":"nature","texture":"mud_bricks.png","common":true},
  {"id":"mud_bricks","name":"Mud Bricks","hex":"#89684f","family":"earth","category":"nature","texture":"mud_bricks.png","common":true},
  {"id":"muddy_mangrove_roots","name":"Muddy Mangrove Roots","hex":"#443b30","family":"earth","category":"nature","texture":"muddy_mangrove_roots_side.png","common":true},
  {"id":"mycelium","name":"Mycelium","hex":"#6f6365","family":"earth","category":"nature","texture":"mycelium_top.png","common":true},
  {"id":"oak_leaves","name":"Oak Leaves","hex":"#43601a","family":"earth","category":"nature","texture":"oak_leaves.png","common":true},
  {"id":"packed_mud","name":"Packed Mud","hex":"#8e6b50","family":"earth","category":"nature","texture":"packed_mud.png","common":true},
  {"id":"pale_moss_block","name":"Pale Moss Block","hex":"#6b7069","family":"earth","category":"nature","texture":"pale_moss_block.png","common":true},
  {"id":"pale_moss_carpet","name":"Pale Moss Carpet","hex":"#6b7069","family":"earth","category":"nature","texture":"pale_moss_carpet.png","common":true},
  {"id":"pale_oak_leaves","name":"Pale Oak Leaves","hex":"#365115","family":"earth","category":"nature","texture":"pale_oak_leaves.png","common":true},
  {"id":"podzol","name":"Podzol","hex":"#5c3f18","family":"earth","category":"nature","texture":"podzol_top.png","common":true},
  {"id":"red_mushroom_block","name":"Red Mushroom Block","hex":"#c82f2d","family":"earth","category":"nature","texture":"red_mushroom_block.png","common":true},
  {"id":"rooted_dirt","name":"Rooted Dirt","hex":"#90684d","family":"earth","category":"nature","texture":"rooted_dirt.png","common":true},
  {"id":"spruce_leaves","name":"Spruce Leaves","hex":"#2f4b2f","family":"earth","category":"nature","texture":"spruce_leaves.png","common":true},
  {"id":"ancient_debris","name":"Ancient Debris","hex":"#604038","family":"earth","category":"nether","texture":"ancient_debris_side.png","common":false},
  {"id":"basalt","name":"Basalt","hex":"#49494e","family":"earth","category":"nether","texture":"basalt_side.png","common":true},
  {"id":"blackstone","name":"Blackstone","hex":"#2a2429","family":"earth","category":"nether","texture":"blackstone.png","common":true},
  {"id":"blackstone_slab","name":"Blackstone Slab","hex":"#2a2429","family":"earth","category":"nether","texture":"blackstone.png","common":true},
  {"id":"blackstone_stairs","name":"Blackstone Stairs","hex":"#2a2429","family":"earth","category":"nether","texture":"blackstone.png","common":true},
  {"id":"chiseled_nether_bricks","name":"Chiseled Nether Bricks","hex":"#2e171b","family":"earth","category":"nether","texture":"chiseled_nether_bricks.png","common":true},
  {"id":"chiseled_polished_blackstone","name":"Chiseled Polished Blackstone","hex":"#363139","family":"earth","category":"nether","texture":"chiseled_polished_blackstone.png","common":true},
  {"id":"cracked_nether_bricks","name":"Cracked Nether Bricks","hex":"#281418","family":"earth","category":"nether","texture":"cracked_nether_bricks.png","common":true},
  {"id":"cracked_polished_blackstone_bricks","name":"Cracked Polished Blackstone Bricks","hex":"#2c262c","family":"earth","category":"nether","texture":"cracked_polished_blackstone_bricks.png","common":true},
  {"id":"crimson_nylium","name":"Crimson Nylium","hex":"#831f1f","family":"earth","category":"nether","texture":"crimson_nylium.png","common":true},
  {"id":"gilded_blackstone","name":"Gilded Blackstone","hex":"#382b26","family":"earth","category":"nether","texture":"gilded_blackstone.png","common":true},
  {"id":"glowstone","name":"Glowstone","hex":"#ac8354","family":"earth","category":"nether","texture":"glowstone.png","common":true},
  {"id":"magma","name":"Magma","hex":"#8f3f20","family":"earth","category":"nether","texture":"magma.png","common":true},
  {"id":"nether_brick_slab","name":"Nether Brick Slab","hex":"#2c161a","family":"earth","category":"nether","texture":"nether_bricks.png","common":true},
  {"id":"nether_brick_stairs","name":"Nether Brick Stairs","hex":"#2c161a","family":"earth","category":"nether","texture":"nether_bricks.png","common":true},
  {"id":"nether_bricks","name":"Nether Bricks","hex":"#2c161a","family":"earth","category":"nether","texture":"nether_bricks.png","common":true},
  {"id":"nether_wart_block","name":"Nether Wart Block","hex":"#730302","family":"earth","category":"nether","texture":"nether_wart_block.png","common":true},
  {"id":"netherite_block","name":"Netherite Block","hex":"#433d40","family":"earth","category":"nether","texture":"netherite_block.png","common":false},
  {"id":"netherrack","name":"Netherrack","hex":"#622626","family":"earth","category":"nether","texture":"netherrack.png","common":true},
  {"id":"polished_basalt","name":"Polished Basalt","hex":"#59585c","family":"earth","category":"nether","texture":"polished_basalt_side.png","common":true},
  {"id":"polished_blackstone","name":"Polished Blackstone","hex":"#353139","family":"earth","category":"nether","texture":"polished_blackstone.png","common":true},
  {"id":"polished_blackstone_brick_slab","name":"Polished Blackstone Brick Slab","hex":"#302b32","family":"earth","category":"nether","texture":"polished_blackstone_bricks.png","common":true},
  {"id":"polished_blackstone_brick_stairs","name":"Polished Blackstone Brick Stairs","hex":"#302b32","family":"earth","category":"nether","texture":"polished_blackstone_bricks.png","common":true},
  {"id":"polished_blackstone_bricks","name":"Polished Blackstone Bricks","hex":"#302b32","family":"earth","category":"nether","texture":"polished_blackstone_bricks.png","common":true},
  {"id":"polished_blackstone_slab","name":"Polished Blackstone Slab","hex":"#353139","family":"earth","category":"nether","texture":"polished_blackstone.png","common":true},
  {"id":"polished_blackstone_stairs","name":"Polished Blackstone Stairs","hex":"#353139","family":"earth","category":"nether","texture":"polished_blackstone.png","common":true},
  {"id":"red_nether_brick_slab","name":"Red Nether Brick Slab","hex":"#460709","family":"earth","category":"nether","texture":"red_nether_bricks.png","common":true},
  {"id":"red_nether_brick_stairs","name":"Red Nether Brick Stairs","hex":"#460709","family":"earth","category":"nether","texture":"red_nether_bricks.png","common":true},
  {"id":"red_nether_bricks","name":"Red Nether Bricks","hex":"#460709","family":"earth","category":"nether","texture":"red_nether_bricks.png","common":true},
  {"id":"shroomlight","name":"Shroomlight","hex":"#f19347","family":"earth","category":"nether","texture":"shroomlight.png","common":true},
  {"id":"smooth_basalt","name":"Smooth Basalt","hex":"#49484e","family":"earth","category":"nether","texture":"smooth_basalt.png","common":true},
  {"id":"soul_sand","name":"Soul Sand","hex":"#513e33","family":"earth","category":"nether","texture":"soul_sand.png","common":true},
  {"id":"soul_soil","name":"Soul Soil","hex":"#4c3a2f","family":"earth","category":"nether","texture":"soul_soil.png","common":true},
  {"id":"warped_nylium","name":"Warped Nylium","hex":"#2b7265","family":"earth","category":"nether","texture":"warped_nylium.png","common":true},
  {"id":"warped_wart_block","name":"Warped Wart Block","hex":"#177879","family":"earth","category":"nether","texture":"warped_wart_block.png","common":true},
  {"id":"dark_prismarine","name":"Dark Prismarine","hex":"#345c4c","family":"ocean","category":"prismarine","texture":"dark_prismarine.png","common":true},
  {"id":"dark_prismarine_slab","name":"Dark Prismarine Slab","hex":"#345c4c","family":"ocean","category":"prismarine","texture":"dark_prismarine.png","common":true},
  {"id":"dark_prismarine_stairs","name":"Dark Prismarine Stairs","hex":"#345c4c","family":"ocean","category":"prismarine","texture":"dark_prismarine.png","common":true},
  {"id":"prismarine","name":"Prismarine","hex":"#639c97","family":"ocean","category":"prismarine","texture":"prismarine.png","common":true},
  {"id":"prismarine_brick_slab","name":"Prismarine Brick Slab","hex":"#63ac9e","family":"ocean","category":"prismarine","texture":"prismarine_bricks.png","common":true},
  {"id":"prismarine_brick_stairs","name":"Prismarine Brick Stairs","hex":"#63ac9e","family":"ocean","category":"prismarine","texture":"prismarine_bricks.png","common":true},
  {"id":"prismarine_bricks","name":"Prismarine Bricks","hex":"#63ac9e","family":"ocean","category":"prismarine","texture":"prismarine_bricks.png","common":true},
  {"id":"prismarine_slab","name":"Prismarine Slab","hex":"#639c97","family":"ocean","category":"prismarine","texture":"prismarine.png","common":true},
  {"id":"prismarine_stairs","name":"Prismarine Stairs","hex":"#639c97","family":"ocean","category":"prismarine","texture":"prismarine.png","common":true},
  {"id":"sea_lantern","name":"Sea Lantern","hex":"#acc8be","family":"ocean","category":"prismarine","texture":"sea_lantern.png","common":false},
  {"id":"chiseled_red_sandstone","name":"Chiseled Red Sandstone","hex":"#b7611c","family":"earth","category":"sand","texture":"chiseled_red_sandstone.png","common":true},
  {"id":"chiseled_sandstone","name":"Chiseled Sandstone","hex":"#d8cb9b","family":"earth","category":"sand","texture":"chiseled_sandstone.png","common":true},
  {"id":"cut_red_sandstone","name":"Cut Red Sandstone","hex":"#bd6620","family":"earth","category":"sand","texture":"cut_red_sandstone.png","common":true},
  {"id":"cut_red_sandstone_slab","name":"Cut Red Sandstone Slab","hex":"#bd6620","family":"earth","category":"sand","texture":"cut_red_sandstone.png","common":true},
  {"id":"cut_sandstone","name":"Cut Sandstone","hex":"#dacea0","family":"earth","category":"sand","texture":"cut_sandstone.png","common":true},
  {"id":"cut_sandstone_slab","name":"Cut Sandstone Slab","hex":"#dacea0","family":"earth","category":"sand","texture":"cut_sandstone.png","common":true},
  {"id":"red_sand","name":"Red Sand","hex":"#bf6721","family":"earth","category":"sand","texture":"red_sand.png","common":true},
  {"id":"red_sandstone","name":"Red Sandstone","hex":"#bb631d","family":"earth","category":"sand","texture":"red_sandstone.png","common":true},
  {"id":"red_sandstone_slab","name":"Red Sandstone Slab","hex":"#bb631d","family":"earth","category":"sand","texture":"red_sandstone.png","common":true},
  {"id":"red_sandstone_stairs","name":"Red Sandstone Stairs","hex":"#bb631d","family":"earth","category":"sand","texture":"red_sandstone.png","common":true},
  {"id":"sand","name":"Sand","hex":"#dbcfa3","family":"earth","category":"sand","texture":"sand.png","common":true},
  {"id":"sandstone","name":"Sandstone","hex":"#d8cb9c","family":"earth","category":"sand","texture":"sandstone.png","common":true},
  {"id":"sandstone_slab","name":"Sandstone Slab","hex":"#d8cb9c","family":"earth","category":"sand","texture":"sandstone.png","common":true},
  {"id":"sandstone_stairs","name":"Sandstone Stairs","hex":"#d8cb9c","family":"earth","category":"sand","texture":"sandstone.png","common":true},
  {"id":"sculk","name":"Sculk","hex":"#0d1e24","family":"earth","category":"sculk","texture":"sculk.png","common":false},
  {"id":"sculk_catalyst","name":"Sculk Catalyst","hex":"#0f2026","family":"earth","category":"sculk","texture":"sculk_catalyst_top.png","common":false},
  {"id":"sculk_vein","name":"Sculk Vein","hex":"#08303a","family":"earth","category":"sculk","texture":"sculk_vein.png","common":false},
  {"id":"black_shulker_box","name":"Black Shulker Box","hex":"#19191e","family":"color","category":"shulker","texture":"black_shulker_box.png","common":false},
  {"id":"blue_shulker_box","name":"Blue Shulker Box","hex":"#2c2e8c","family":"color","category":"shulker","texture":"blue_shulker_box.png","common":false},
  {"id":"brown_shulker_box","name":"Brown Shulker Box","hex":"#6a4224","family":"color","category":"shulker","texture":"brown_shulker_box.png","common":false},
  {"id":"cyan_shulker_box","name":"Cyan Shulker Box","hex":"#147987","family":"color","category":"shulker","texture":"cyan_shulker_box.png","common":false},
  {"id":"gray_shulker_box","name":"Gray Shulker Box","hex":"#373b3e","family":"color","category":"shulker","texture":"gray_shulker_box.png","common":false},
  {"id":"green_shulker_box","name":"Green Shulker Box","hex":"#4f6520","family":"color","category":"shulker","texture":"green_shulker_box.png","common":false},
  {"id":"light_blue_shulker_box","name":"Light Blue Shulker Box","hex":"#31a4d4","family":"color","category":"shulker","texture":"light_blue_shulker_box.png","common":false},
  {"id":"light_gray_shulker_box","name":"Light Gray Shulker Box","hex":"#7c7c73","family":"color","category":"shulker","texture":"light_gray_shulker_box.png","common":false},
  {"id":"lime_shulker_box","name":"Lime Shulker Box","hex":"#64ad17","family":"color","category":"shulker","texture":"lime_shulker_box.png","common":false},
  {"id":"magenta_shulker_box","name":"Magenta Shulker Box","hex":"#ae36a4","family":"color","category":"shulker","texture":"magenta_shulker_box.png","common":false},
  {"id":"orange_shulker_box","name":"Orange Shulker Box","hex":"#ea6a09","family":"color","category":"shulker","texture":"orange_shulker_box.png","common":false},
  {"id":"pink_shulker_box","name":"Pink Shulker Box","hex":"#e67a9e","family":"color","category":"shulker","texture":"pink_shulker_box.png","common":false},
  {"id":"purple_shulker_box","name":"Purple Shulker Box","hex":"#67209c","family":"color","category":"shulker","texture":"purple_shulker_box.png","common":false},
  {"id":"red_shulker_box","name":"Red Shulker Box","hex":"#8c1f1e","family":"color","category":"shulker","texture":"red_shulker_box.png","common":false},
  {"id":"shulker_box","name":"Shulker Box","hex":"#8b618b","family":"color","category":"shulker","texture":"shulker_box.png","common":false},
  {"id":"white_shulker_box","name":"White Shulker Box","hex":"#d8dddd","family":"color","category":"shulker","texture":"white_shulker_box.png","common":false},
  {"id":"yellow_shulker_box","name":"Yellow Shulker Box","hex":"#f8bd1d","family":"color","category":"shulker","texture":"yellow_shulker_box.png","common":false},
  {"id":"andesite","name":"Andesite","hex":"#888889","family":"stone","category":"stone","texture":"andesite.png","common":true},
  {"id":"andesite_slab","name":"Andesite Slab","hex":"#888889","family":"stone","category":"stone","texture":"andesite.png","common":true},
  {"id":"andesite_stairs","name":"Andesite Stairs","hex":"#888889","family":"stone","category":"stone","texture":"andesite.png","common":true},
  {"id":"bedrock","name":"Bedrock","hex":"#555555","family":"stone","category":"stone","texture":"bedrock.png","common":true},
  {"id":"calcite","name":"Calcite","hex":"#dfe0dd","family":"stone","category":"stone","texture":"calcite.png","common":true},
  {"id":"chiseled_stone_bricks","name":"Chiseled Stone Bricks","hex":"#787778","family":"stone","category":"stone","texture":"chiseled_stone_bricks.png","common":true},
  {"id":"cobblestone","name":"Cobblestone","hex":"#807f80","family":"stone","category":"stone","texture":"cobblestone.png","common":true},
  {"id":"cobblestone_slab","name":"Cobblestone Slab","hex":"#807f80","family":"stone","category":"stone","texture":"cobblestone.png","common":true},
  {"id":"cobblestone_stairs","name":"Cobblestone Stairs","hex":"#807f80","family":"stone","category":"stone","texture":"cobblestone.png","common":true},
  {"id":"cracked_stone_bricks","name":"Cracked Stone Bricks","hex":"#767676","family":"stone","category":"stone","texture":"cracked_stone_bricks.png","common":true},
  {"id":"diorite","name":"Diorite","hex":"#bdbcbd","family":"stone","category":"stone","texture":"diorite.png","common":true},
  {"id":"diorite_slab","name":"Diorite Slab","hex":"#bdbcbd","family":"stone","category":"stone","texture":"diorite.png","common":true},
  {"id":"diorite_stairs","name":"Diorite Stairs","hex":"#bdbcbd","family":"stone","category":"stone","texture":"diorite.png","common":true},
  {"id":"dripstone_block","name":"Dripstone Block","hex":"#866c5d","family":"stone","category":"stone","texture":"dripstone_block.png","common":true},
  {"id":"granite","name":"Granite","hex":"#956756","family":"stone","category":"stone","texture":"granite.png","common":true},
  {"id":"granite_slab","name":"Granite Slab","hex":"#956756","family":"stone","category":"stone","texture":"granite.png","common":true},
  {"id":"granite_stairs","name":"Granite Stairs","hex":"#956756","family":"stone","category":"stone","texture":"granite.png","common":true},
  {"id":"mossy_cobblestone","name":"Mossy Cobblestone","hex":"#6e775f","family":"stone","category":"stone","texture":"mossy_cobblestone.png","common":true},
  {"id":"mossy_cobblestone_slab","name":"Mossy Cobblestone Slab","hex":"#6e775f","family":"stone","category":"stone","texture":"mossy_cobblestone.png","common":true},
  {"id":"mossy_cobblestone_stairs","name":"Mossy Cobblestone Stairs","hex":"#6e775f","family":"stone","category":"stone","texture":"mossy_cobblestone.png","common":true},
  {"id":"mossy_stone_brick_slab","name":"Mossy Stone Brick Slab","hex":"#737969","family":"stone","category":"stone","texture":"mossy_stone_bricks.png","common":true},
  {"id":"mossy_stone_brick_stairs","name":"Mossy Stone Brick Stairs","hex":"#737969","family":"stone","category":"stone","texture":"mossy_stone_bricks.png","common":true},
  {"id":"mossy_stone_bricks","name":"Mossy Stone Bricks","hex":"#737969","family":"stone","category":"stone","texture":"mossy_stone_bricks.png","common":true},
  {"id":"polished_andesite","name":"Polished Andesite","hex":"#848786","family":"stone","category":"stone","texture":"polished_andesite.png","common":true},
  {"id":"polished_andesite_slab","name":"Polished Andesite Slab","hex":"#848786","family":"stone","category":"stone","texture":"polished_andesite.png","common":true},
  {"id":"polished_andesite_stairs","name":"Polished Andesite Stairs","hex":"#848786","family":"stone","category":"stone","texture":"polished_andesite.png","common":true},
  {"id":"polished_diorite","name":"Polished Diorite","hex":"#c1c1c3","family":"stone","category":"stone","texture":"polished_diorite.png","common":true},
  {"id":"polished_diorite_slab","name":"Polished Diorite Slab","hex":"#c1c1c3","family":"stone","category":"stone","texture":"polished_diorite.png","common":true},
  {"id":"polished_diorite_stairs","name":"Polished Diorite Stairs","hex":"#c1c1c3","family":"stone","category":"stone","texture":"polished_diorite.png","common":true},
  {"id":"polished_granite","name":"Polished Granite","hex":"#9a6b59","family":"stone","category":"stone","texture":"polished_granite.png","common":true},
  {"id":"polished_granite_slab","name":"Polished Granite Slab","hex":"#9a6b59","family":"stone","category":"stone","texture":"polished_granite.png","common":true},
  {"id":"polished_granite_stairs","name":"Polished Granite Stairs","hex":"#9a6b59","family":"stone","category":"stone","texture":"polished_granite.png","common":true},
  {"id":"smooth_stone","name":"Smooth Stone","hex":"#9f9f9f","family":"stone","category":"stone","texture":"smooth_stone.png","common":true},
  {"id":"smooth_stone_slab","name":"Smooth Stone Slab","hex":"#9f9f9f","family":"stone","category":"stone","texture":"smooth_stone.png","common":true},
  {"id":"stone","name":"Stone","hex":"#7e7e7e","family":"stone","category":"stone","texture":"stone.png","common":true},
  {"id":"stone_brick_slab","name":"Stone Brick Slab","hex":"#7a7a7a","family":"stone","category":"stone","texture":"stone_bricks.png","common":true},
  {"id":"stone_brick_stairs","name":"Stone Brick Stairs","hex":"#7a7a7a","family":"stone","category":"stone","texture":"stone_bricks.png","common":true},
  {"id":"stone_bricks","name":"Stone Bricks","hex":"#7a7a7a","family":"stone","category":"stone","texture":"stone_bricks.png","common":true},
  {"id":"stone_slab","name":"Stone Slab","hex":"#7e7e7e","family":"stone","category":"stone","texture":"stone.png","common":true},
  {"id":"stone_stairs","name":"Stone Stairs","hex":"#7e7e7e","family":"stone","category":"stone","texture":"stone.png","common":true},
  {"id":"stonecutter","name":"Stonecutter","hex":"#6b5a4e","family":"stone","category":"stone","texture":"stonecutter_side.png","common":true},
  {"id":"black_glazed_terracotta","name":"Black Glazed Terracotta","hex":"#441e20","family":"color","category":"terracotta","texture":"black_glazed_terracotta.png","common":true},
  {"id":"black_terracotta","name":"Black Terracotta","hex":"#251710","family":"color","category":"terracotta","texture":"black_terracotta.png","common":true},
  {"id":"blue_glazed_terracotta","name":"Blue Glazed Terracotta","hex":"#2f418b","family":"color","category":"terracotta","texture":"blue_glazed_terracotta.png","common":true},
  {"id":"blue_terracotta","name":"Blue Terracotta","hex":"#4a3c5b","family":"color","category":"terracotta","texture":"blue_terracotta.png","common":true},
  {"id":"brown_glazed_terracotta","name":"Brown Glazed Terracotta","hex":"#786a56","family":"color","category":"terracotta","texture":"brown_glazed_terracotta.png","common":true},
  {"id":"brown_terracotta","name":"Brown Terracotta","hex":"#4d3324","family":"color","category":"terracotta","texture":"brown_terracotta.png","common":true},
  {"id":"cyan_glazed_terracotta","name":"Cyan Glazed Terracotta","hex":"#34777d","family":"color","category":"terracotta","texture":"cyan_glazed_terracotta.png","common":true},
  {"id":"cyan_terracotta","name":"Cyan Terracotta","hex":"#575b5b","family":"color","category":"terracotta","texture":"cyan_terracotta.png","common":true},
  {"id":"gray_glazed_terracotta","name":"Gray Glazed Terracotta","hex":"#535a5e","family":"color","category":"terracotta","texture":"gray_glazed_terracotta.png","common":true},
  {"id":"gray_terracotta","name":"Gray Terracotta","hex":"#3a2a24","family":"color","category":"terracotta","texture":"gray_terracotta.png","common":true},
  {"id":"green_glazed_terracotta","name":"Green Glazed Terracotta","hex":"#758e43","family":"color","category":"terracotta","texture":"green_glazed_terracotta.png","common":true},
  {"id":"green_terracotta","name":"Green Terracotta","hex":"#4c532a","family":"color","category":"terracotta","texture":"green_terracotta.png","common":true},
  {"id":"light_blue_glazed_terracotta","name":"Light Blue Glazed Terracotta","hex":"#5fa5d1","family":"color","category":"terracotta","texture":"light_blue_glazed_terracotta.png","common":true},
  {"id":"light_blue_terracotta","name":"Light Blue Terracotta","hex":"#716d8a","family":"color","category":"terracotta","texture":"light_blue_terracotta.png","common":true},
  {"id":"light_gray_glazed_terracotta","name":"Light Gray Glazed Terracotta","hex":"#90a6a8","family":"color","category":"terracotta","texture":"light_gray_glazed_terracotta.png","common":true},
  {"id":"light_gray_terracotta","name":"Light Gray Terracotta","hex":"#876b62","family":"color","category":"terracotta","texture":"light_gray_terracotta.png","common":true},
  {"id":"lime_glazed_terracotta","name":"Lime Glazed Terracotta","hex":"#a3c637","family":"color","category":"terracotta","texture":"lime_glazed_terracotta.png","common":true},
  {"id":"lime_terracotta","name":"Lime Terracotta","hex":"#687635","family":"color","category":"terracotta","texture":"lime_terracotta.png","common":true},
  {"id":"magenta_glazed_terracotta","name":"Magenta Glazed Terracotta","hex":"#d064c0","family":"color","category":"terracotta","texture":"magenta_glazed_terracotta.png","common":true},
  {"id":"magenta_terracotta","name":"Magenta Terracotta","hex":"#96586d","family":"color","category":"terracotta","texture":"magenta_terracotta.png","common":true},
  {"id":"orange_glazed_terracotta","name":"Orange Glazed Terracotta","hex":"#9b935c","family":"color","category":"terracotta","texture":"orange_glazed_terracotta.png","common":true},
  {"id":"orange_terracotta","name":"Orange Terracotta","hex":"#a25426","family":"color","category":"terracotta","texture":"orange_terracotta.png","common":true},
  {"id":"pink_glazed_terracotta","name":"Pink Glazed Terracotta","hex":"#eb9bb6","family":"color","category":"terracotta","texture":"pink_glazed_terracotta.png","common":true},
  {"id":"pink_terracotta","name":"Pink Terracotta","hex":"#a24e4f","family":"color","category":"terracotta","texture":"pink_terracotta.png","common":true},
  {"id":"purple_glazed_terracotta","name":"Purple Glazed Terracotta","hex":"#6e3098","family":"color","category":"terracotta","texture":"purple_glazed_terracotta.png","common":true},
  {"id":"purple_terracotta","name":"Purple Terracotta","hex":"#764656","family":"color","category":"terracotta","texture":"purple_terracotta.png","common":true},
  {"id":"red_glazed_terracotta","name":"Red Glazed Terracotta","hex":"#b63c35","family":"color","category":"terracotta","texture":"red_glazed_terracotta.png","common":true},
  {"id":"red_terracotta","name":"Red Terracotta","hex":"#8f3d2f","family":"color","category":"terracotta","texture":"red_terracotta.png","common":true},
  {"id":"terracotta","name":"Terracotta","hex":"#985e44","family":"color","category":"terracotta","texture":"terracotta.png","common":true},
  {"id":"white_glazed_terracotta","name":"White Glazed Terracotta","hex":"#bdd4cb","family":"color","category":"terracotta","texture":"white_glazed_terracotta.png","common":true},
  {"id":"white_terracotta","name":"White Terracotta","hex":"#d2b2a1","family":"color","category":"terracotta","texture":"white_terracotta.png","common":true},
  {"id":"yellow_glazed_terracotta","name":"Yellow Glazed Terracotta","hex":"#eac059","family":"color","category":"terracotta","texture":"yellow_glazed_terracotta.png","common":true},
  {"id":"yellow_terracotta","name":"Yellow Terracotta","hex":"#ba8523","family":"color","category":"terracotta","texture":"yellow_terracotta.png","common":true},
  {"id":"chiseled_tuff","name":"Chiseled Tuff","hex":"#595e57","family":"stone","category":"tuff","texture":"chiseled_tuff.png","common":true},
  {"id":"chiseled_tuff_bricks","name":"Chiseled Tuff Bricks","hex":"#636760","family":"stone","category":"tuff","texture":"chiseled_tuff_bricks.png","common":true},
  {"id":"polished_tuff","name":"Polished Tuff","hex":"#626864","family":"stone","category":"tuff","texture":"polished_tuff.png","common":true},
  {"id":"polished_tuff_slab","name":"Polished Tuff Slab","hex":"#626864","family":"stone","category":"tuff","texture":"polished_tuff.png","common":true},
  {"id":"polished_tuff_stairs","name":"Polished Tuff Stairs","hex":"#626864","family":"stone","category":"tuff","texture":"polished_tuff.png","common":true},
  {"id":"tuff","name":"Tuff","hex":"#6c6d67","family":"stone","category":"tuff","texture":"tuff.png","common":true},
  {"id":"tuff_brick_slab","name":"Tuff Brick Slab","hex":"#62675f","family":"stone","category":"tuff","texture":"tuff_bricks.png","common":true},
  {"id":"tuff_brick_stairs","name":"Tuff Brick Stairs","hex":"#62675f","family":"stone","category":"tuff","texture":"tuff_bricks.png","common":true},
  {"id":"tuff_bricks","name":"Tuff Bricks","hex":"#62675f","family":"stone","category":"tuff","texture":"tuff_bricks.png","common":true},
  {"id":"tuff_slab","name":"Tuff Slab","hex":"#6c6d67","family":"stone","category":"tuff","texture":"tuff.png","common":true},
  {"id":"tuff_stairs","name":"Tuff Stairs","hex":"#6c6d67","family":"stone","category":"tuff","texture":"tuff.png","common":true},
  {"id":"acacia_log","name":"Acacia Log","hex":"#676157","family":"wood","category":"wood","texture":"acacia_log.png","common":true},
  {"id":"acacia_planks","name":"Acacia Planks","hex":"#a85a32","family":"wood","category":"wood","texture":"acacia_planks.png","common":true},
  {"id":"acacia_shelf","name":"Acacia Shelf","hex":"#9d5635","family":"wood","category":"wood","texture":"acacia_shelf_front.png","common":true},
  {"id":"acacia_slab","name":"Acacia Slab","hex":"#a85a32","family":"wood","category":"wood","texture":"acacia_planks.png","common":true},
  {"id":"acacia_stairs","name":"Acacia Stairs","hex":"#a85a32","family":"wood","category":"wood","texture":"acacia_planks.png","common":true},
  {"id":"acacia_trapdoor","name":"Acacia Trapdoor","hex":"#9d5733","family":"wood","category":"wood","texture":"acacia_trapdoor.png","common":true},
  {"id":"acacia_wood","name":"Acacia Wood","hex":"#676157","family":"wood","category":"wood","texture":"acacia_log.png","common":true},
  {"id":"bamboo_block","name":"Bamboo Block","hex":"#7f903a","family":"wood","category":"wood","texture":"bamboo_block.png","common":true},
  {"id":"bamboo_mosaic","name":"Bamboo Mosaic","hex":"#beaa4e","family":"wood","category":"wood","texture":"bamboo_mosaic.png","common":true},
  {"id":"bamboo_mosaic_slab","name":"Bamboo Mosaic Slab","hex":"#beaa4e","family":"wood","category":"wood","texture":"bamboo_mosaic.png","common":true},
  {"id":"bamboo_mosaic_stairs","name":"Bamboo Mosaic Stairs","hex":"#beaa4e","family":"wood","category":"wood","texture":"bamboo_mosaic.png","common":true},
  {"id":"bamboo_planks","name":"Bamboo Planks","hex":"#c1ad50","family":"wood","category":"wood","texture":"bamboo_planks.png","common":true},
  {"id":"bamboo_shelf","name":"Bamboo Shelf","hex":"#baa74d","family":"wood","category":"wood","texture":"bamboo_shelf_front.png","common":true},
  {"id":"bamboo_slab","name":"Bamboo Slab","hex":"#c1ad50","family":"wood","category":"wood","texture":"bamboo_planks.png","common":true},
  {"id":"bamboo_stairs","name":"Bamboo Stairs","hex":"#c1ad50","family":"wood","category":"wood","texture":"bamboo_planks.png","common":true},
  {"id":"bamboo_trapdoor","name":"Bamboo Trapdoor","hex":"#c7b355","family":"wood","category":"wood","texture":"bamboo_trapdoor.png","common":true},
  {"id":"birch_log","name":"Birch Log","hex":"#d9d7d2","family":"wood","category":"wood","texture":"birch_log.png","common":true},
  {"id":"birch_planks","name":"Birch Planks","hex":"#c0af79","family":"wood","category":"wood","texture":"birch_planks.png","common":true},
  {"id":"birch_shelf","name":"Birch Shelf","hex":"#b39f6c","family":"wood","category":"wood","texture":"birch_shelf_front.png","common":true},
  {"id":"birch_slab","name":"Birch Slab","hex":"#c0af79","family":"wood","category":"wood","texture":"birch_planks.png","common":true},
  {"id":"birch_stairs","name":"Birch Stairs","hex":"#c0af79","family":"wood","category":"wood","texture":"birch_planks.png","common":true},
  {"id":"birch_trapdoor","name":"Birch Trapdoor","hex":"#cfc29d","family":"wood","category":"wood","texture":"birch_trapdoor.png","common":true},
  {"id":"birch_wood","name":"Birch Wood","hex":"#d9d7d2","family":"wood","category":"wood","texture":"birch_log.png","common":true},
  {"id":"cherry_log","name":"Cherry Log","hex":"#37212c","family":"wood","category":"wood","texture":"cherry_log.png","common":true},
  {"id":"cherry_planks","name":"Cherry Planks","hex":"#e3b3ad","family":"wood","category":"wood","texture":"cherry_planks.png","common":true},
  {"id":"cherry_shelf","name":"Cherry Shelf","hex":"#cc8585","family":"wood","category":"wood","texture":"cherry_shelf_front.png","common":true},
  {"id":"cherry_slab","name":"Cherry Slab","hex":"#e3b3ad","family":"wood","category":"wood","texture":"cherry_planks.png","common":true},
  {"id":"cherry_stairs","name":"Cherry Stairs","hex":"#e3b3ad","family":"wood","category":"wood","texture":"cherry_planks.png","common":true},
  {"id":"cherry_trapdoor","name":"Cherry Trapdoor","hex":"#e2b3ac","family":"wood","category":"wood","texture":"cherry_trapdoor.png","common":true},
  {"id":"cherry_wood","name":"Cherry Wood","hex":"#37212c","family":"wood","category":"wood","texture":"cherry_log.png","common":true},
  {"id":"crimson_hyphae","name":"Crimson Hyphae","hex":"#5d1a1e","family":"wood","category":"wood","texture":"crimson_stem.png","common":true},
  {"id":"crimson_planks","name":"Crimson Planks","hex":"#653147","family":"wood","category":"wood","texture":"crimson_planks.png","common":true},
  {"id":"crimson_shelf","name":"Crimson Shelf","hex":"#843655","family":"wood","category":"wood","texture":"crimson_shelf_front.png","common":true},
  {"id":"crimson_slab","name":"Crimson Slab","hex":"#653147","family":"wood","category":"wood","texture":"crimson_planks.png","common":true},
  {"id":"crimson_stairs","name":"Crimson Stairs","hex":"#653147","family":"wood","category":"wood","texture":"crimson_planks.png","common":true},
  {"id":"crimson_stem","name":"Crimson Stem","hex":"#5d1a1e","family":"wood","category":"wood","texture":"crimson_stem.png","common":true},
  {"id":"crimson_trapdoor","name":"Crimson Trapdoor","hex":"#683348","family":"wood","category":"wood","texture":"crimson_trapdoor.png","common":true},
  {"id":"dark_oak_log","name":"Dark Oak Log","hex":"#3c2f1a","family":"wood","category":"wood","texture":"dark_oak_log.png","common":true},
  {"id":"dark_oak_planks","name":"Dark Oak Planks","hex":"#432b14","family":"wood","category":"wood","texture":"dark_oak_planks.png","common":true},
  {"id":"dark_oak_shelf","name":"Dark Oak Shelf","hex":"#423320","family":"wood","category":"wood","texture":"dark_oak_shelf_front.png","common":true},
  {"id":"dark_oak_slab","name":"Dark Oak Slab","hex":"#432b14","family":"wood","category":"wood","texture":"dark_oak_planks.png","common":true},
  {"id":"dark_oak_stairs","name":"Dark Oak Stairs","hex":"#432b14","family":"wood","category":"wood","texture":"dark_oak_planks.png","common":true},
  {"id":"dark_oak_trapdoor","name":"Dark Oak Trapdoor","hex":"#4b3217","family":"wood","category":"wood","texture":"dark_oak_trapdoor.png","common":true},
  {"id":"dark_oak_wood","name":"Dark Oak Wood","hex":"#3c2f1a","family":"wood","category":"wood","texture":"dark_oak_log.png","common":true},
  {"id":"iron_trapdoor","name":"Iron Trapdoor","hex":"#cbcaca","family":"wood","category":"wood","texture":"iron_trapdoor.png","common":true},
  {"id":"jungle_log","name":"Jungle Log","hex":"#554419","family":"wood","category":"wood","texture":"jungle_log.png","common":true},
  {"id":"jungle_planks","name":"Jungle Planks","hex":"#a07351","family":"wood","category":"wood","texture":"jungle_planks.png","common":true},
  {"id":"jungle_shelf","name":"Jungle Shelf","hex":"#9e7b4b","family":"wood","category":"wood","texture":"jungle_shelf_front.png","common":true},
  {"id":"jungle_slab","name":"Jungle Slab","hex":"#a07351","family":"wood","category":"wood","texture":"jungle_planks.png","common":true},
  {"id":"jungle_stairs","name":"Jungle Stairs","hex":"#a07351","family":"wood","category":"wood","texture":"jungle_planks.png","common":true},
  {"id":"jungle_trapdoor","name":"Jungle Trapdoor","hex":"#996e4d","family":"wood","category":"wood","texture":"jungle_trapdoor.png","common":true},
  {"id":"jungle_wood","name":"Jungle Wood","hex":"#554419","family":"wood","category":"wood","texture":"jungle_log.png","common":true},
  {"id":"mangrove_log","name":"Mangrove Log","hex":"#544329","family":"wood","category":"wood","texture":"mangrove_log.png","common":true},
  {"id":"mangrove_planks","name":"Mangrove Planks","hex":"#763631","family":"wood","category":"wood","texture":"mangrove_planks.png","common":true},
  {"id":"mangrove_shelf","name":"Mangrove Shelf","hex":"#6e2e2b","family":"wood","category":"wood","texture":"mangrove_shelf_front.png","common":true},
  {"id":"mangrove_slab","name":"Mangrove Slab","hex":"#763631","family":"wood","category":"wood","texture":"mangrove_planks.png","common":true},
  {"id":"mangrove_stairs","name":"Mangrove Stairs","hex":"#763631","family":"wood","category":"wood","texture":"mangrove_planks.png","common":true},
  {"id":"mangrove_trapdoor","name":"Mangrove Trapdoor","hex":"#6f2f2a","family":"wood","category":"wood","texture":"mangrove_trapdoor.png","common":true},
  {"id":"mangrove_wood","name":"Mangrove Wood","hex":"#544329","family":"wood","category":"wood","texture":"mangrove_log.png","common":true},
  {"id":"mushroom_stem","name":"Mushroom Stem","hex":"#cbc5ba","family":"wood","category":"wood","texture":"mushroom_stem.png","common":true},
  {"id":"oak_log","name":"Oak Log","hex":"#6d5533","family":"wood","category":"wood","texture":"oak_log.png","common":true},
  {"id":"oak_planks","name":"Oak Planks","hex":"#a2834f","family":"wood","category":"wood","texture":"oak_planks.png","common":true},
  {"id":"oak_shelf","name":"Oak Shelf","hex":"#987947","family":"wood","category":"wood","texture":"oak_shelf_front.png","common":true},
  {"id":"oak_slab","name":"Oak Slab","hex":"#a2834f","family":"wood","category":"wood","texture":"oak_planks.png","common":true},
  {"id":"oak_stairs","name":"Oak Stairs","hex":"#a2834f","family":"wood","category":"wood","texture":"oak_planks.png","common":true},
  {"id":"oak_trapdoor","name":"Oak Trapdoor","hex":"#7d6339","family":"wood","category":"wood","texture":"oak_trapdoor.png","common":true},
  {"id":"oak_wood","name":"Oak Wood","hex":"#6d5533","family":"wood","category":"wood","texture":"oak_log.png","common":true},
  {"id":"pale_oak_log","name":"Pale Oak Log","hex":"#584e4b","family":"wood","category":"wood","texture":"pale_oak_log.png","common":true},
  {"id":"pale_oak_planks","name":"Pale Oak Planks","hex":"#e4dad8","family":"wood","category":"wood","texture":"pale_oak_planks.png","common":true},
  {"id":"pale_oak_shelf","name":"Pale Oak Shelf","hex":"#e8dfde","family":"wood","category":"wood","texture":"pale_oak_shelf_front.png","common":true},
  {"id":"pale_oak_slab","name":"Pale Oak Slab","hex":"#e4dad8","family":"wood","category":"wood","texture":"pale_oak_planks.png","common":true},
  {"id":"pale_oak_stairs","name":"Pale Oak Stairs","hex":"#e4dad8","family":"wood","category":"wood","texture":"pale_oak_planks.png","common":true},
  {"id":"pale_oak_trapdoor","name":"Pale Oak Trapdoor","hex":"#e6dcdb","family":"wood","category":"wood","texture":"pale_oak_trapdoor.png","common":true},
  {"id":"pale_oak_wood","name":"Pale Oak Wood","hex":"#584e4b","family":"wood","category":"wood","texture":"pale_oak_log.png","common":true},
  {"id":"spruce_log","name":"Spruce Log","hex":"#3b2611","family":"wood","category":"wood","texture":"spruce_log.png","common":true},
  {"id":"spruce_planks","name":"Spruce Planks","hex":"#735531","family":"wood","category":"wood","texture":"spruce_planks.png","common":true},
  {"id":"spruce_shelf","name":"Spruce Shelf","hex":"#675230","family":"wood","category":"wood","texture":"spruce_shelf_front.png","common":true},
  {"id":"spruce_slab","name":"Spruce Slab","hex":"#735531","family":"wood","category":"wood","texture":"spruce_planks.png","common":true},
  {"id":"spruce_stairs","name":"Spruce Stairs","hex":"#735531","family":"wood","category":"wood","texture":"spruce_planks.png","common":true},
  {"id":"spruce_trapdoor","name":"Spruce Trapdoor","hex":"#684f30","family":"wood","category":"wood","texture":"spruce_trapdoor.png","common":true},
  {"id":"spruce_wood","name":"Spruce Wood","hex":"#3b2611","family":"wood","category":"wood","texture":"spruce_log.png","common":true},
  {"id":"stripped_acacia_log","name":"Stripped Acacia Log","hex":"#af5d3c","family":"wood","category":"wood","texture":"stripped_acacia_log.png","common":true},
  {"id":"stripped_acacia_wood","name":"Stripped Acacia Wood","hex":"#af5d3c","family":"wood","category":"wood","texture":"stripped_acacia_log.png","common":true},
  {"id":"stripped_bamboo_block","name":"Stripped Bamboo Block","hex":"#c1ad50","family":"wood","category":"wood","texture":"stripped_bamboo_block.png","common":true},
  {"id":"stripped_birch_log","name":"Stripped Birch Log","hex":"#c5b076","family":"wood","category":"wood","texture":"stripped_birch_log.png","common":true},
  {"id":"stripped_birch_wood","name":"Stripped Birch Wood","hex":"#c5b076","family":"wood","category":"wood","texture":"stripped_birch_log.png","common":true},
  {"id":"stripped_cherry_log","name":"Stripped Cherry Log","hex":"#d79195","family":"wood","category":"wood","texture":"stripped_cherry_log.png","common":true},
  {"id":"stripped_cherry_wood","name":"Stripped Cherry Wood","hex":"#d79195","family":"wood","category":"wood","texture":"stripped_cherry_log.png","common":true},
  {"id":"stripped_crimson_hyphae","name":"Stripped Crimson Hyphae","hex":"#89395a","family":"wood","category":"wood","texture":"stripped_crimson_stem.png","common":true},
  {"id":"stripped_crimson_stem","name":"Stripped Crimson Stem","hex":"#89395a","family":"wood","category":"wood","texture":"stripped_crimson_stem.png","common":true},
  {"id":"stripped_dark_oak_log","name":"Stripped Dark Oak Log","hex":"#493924","family":"wood","category":"wood","texture":"stripped_dark_oak_log.png","common":true},
  {"id":"stripped_dark_oak_wood","name":"Stripped Dark Oak Wood","hex":"#493924","family":"wood","category":"wood","texture":"stripped_dark_oak_log.png","common":true},
  {"id":"stripped_jungle_log","name":"Stripped Jungle Log","hex":"#ab8555","family":"wood","category":"wood","texture":"stripped_jungle_log.png","common":true},
  {"id":"stripped_jungle_wood","name":"Stripped Jungle Wood","hex":"#ab8555","family":"wood","category":"wood","texture":"stripped_jungle_log.png","common":true},
  {"id":"stripped_mangrove_log","name":"Stripped Mangrove Log","hex":"#783630","family":"wood","category":"wood","texture":"stripped_mangrove_log.png","common":true},
  {"id":"stripped_mangrove_wood","name":"Stripped Mangrove Wood","hex":"#783630","family":"wood","category":"wood","texture":"stripped_mangrove_log.png","common":true},
  {"id":"stripped_oak_log","name":"Stripped Oak Log","hex":"#b19056","family":"wood","category":"wood","texture":"stripped_oak_log.png","common":true},
  {"id":"stripped_oak_wood","name":"Stripped Oak Wood","hex":"#b19056","family":"wood","category":"wood","texture":"stripped_oak_log.png","common":true},
  {"id":"stripped_pale_oak_log","name":"Stripped Pale Oak Log","hex":"#f6eeed","family":"wood","category":"wood","texture":"stripped_pale_oak_log.png","common":true},
  {"id":"stripped_pale_oak_wood","name":"Stripped Pale Oak Wood","hex":"#f6eeed","family":"wood","category":"wood","texture":"stripped_pale_oak_log.png","common":true},
  {"id":"stripped_spruce_log","name":"Stripped Spruce Log","hex":"#745a34","family":"wood","category":"wood","texture":"stripped_spruce_log.png","common":true},
  {"id":"stripped_spruce_wood","name":"Stripped Spruce Wood","hex":"#745a34","family":"wood","category":"wood","texture":"stripped_spruce_log.png","common":true},
  {"id":"stripped_warped_hyphae","name":"Stripped Warped Hyphae","hex":"#3a9794","family":"wood","category":"wood","texture":"stripped_warped_stem.png","common":true},
  {"id":"stripped_warped_stem","name":"Stripped Warped Stem","hex":"#3a9794","family":"wood","category":"wood","texture":"stripped_warped_stem.png","common":true},
  {"id":"warped_hyphae","name":"Warped Hyphae","hex":"#3a3b4e","family":"wood","category":"wood","texture":"warped_stem.png","common":true},
  {"id":"warped_planks","name":"Warped Planks","hex":"#2b6963","family":"wood","category":"wood","texture":"warped_planks.png","common":true},
  {"id":"warped_shelf","name":"Warped Shelf","hex":"#348e88","family":"wood","category":"wood","texture":"warped_shelf_front.png","common":true},
  {"id":"warped_slab","name":"Warped Slab","hex":"#2b6963","family":"wood","category":"wood","texture":"warped_planks.png","common":true},
  {"id":"warped_stairs","name":"Warped Stairs","hex":"#2b6963","family":"wood","category":"wood","texture":"warped_planks.png","common":true},
  {"id":"warped_stem","name":"Warped Stem","hex":"#3a3b4e","family":"wood","category":"wood","texture":"warped_stem.png","common":true},
  {"id":"warped_trapdoor","name":"Warped Trapdoor","hex":"#2f7870","family":"wood","category":"wood","texture":"warped_trapdoor.png","common":true},
  {"id":"black_carpet","name":"Black Carpet","hex":"#15151a","family":"color","category":"wool","texture":"black_wool.png","common":true},
  {"id":"black_wool","name":"Black Wool","hex":"#15151a","family":"color","category":"wool","texture":"black_wool.png","common":true},
  {"id":"blue_carpet","name":"Blue Carpet","hex":"#35399d","family":"color","category":"wool","texture":"blue_wool.png","common":true},
  {"id":"blue_wool","name":"Blue Wool","hex":"#35399d","family":"color","category":"wool","texture":"blue_wool.png","common":true},
  {"id":"brown_carpet","name":"Brown Carpet","hex":"#724829","family":"color","category":"wool","texture":"brown_wool.png","common":true},
  {"id":"brown_wool","name":"Brown Wool","hex":"#724829","family":"color","category":"wool","texture":"brown_wool.png","common":true},
  {"id":"cyan_carpet","name":"Cyan Carpet","hex":"#158a91","family":"color","category":"wool","texture":"cyan_wool.png","common":true},
  {"id":"cyan_wool","name":"Cyan Wool","hex":"#158a91","family":"color","category":"wool","texture":"cyan_wool.png","common":true},
  {"id":"gray_carpet","name":"Gray Carpet","hex":"#3f4448","family":"color","category":"wool","texture":"gray_wool.png","common":true},
  {"id":"gray_wool","name":"Gray Wool","hex":"#3f4448","family":"color","category":"wool","texture":"gray_wool.png","common":true},
  {"id":"green_carpet","name":"Green Carpet","hex":"#556e1c","family":"color","category":"wool","texture":"green_wool.png","common":true},
  {"id":"green_wool","name":"Green Wool","hex":"#556e1c","family":"color","category":"wool","texture":"green_wool.png","common":true},
  {"id":"light_blue_carpet","name":"Light Blue Carpet","hex":"#3aafd9","family":"color","category":"wool","texture":"light_blue_wool.png","common":true},
  {"id":"light_blue_wool","name":"Light Blue Wool","hex":"#3aafd9","family":"color","category":"wool","texture":"light_blue_wool.png","common":true},
  {"id":"light_gray_carpet","name":"Light Gray Carpet","hex":"#8e8e87","family":"color","category":"wool","texture":"light_gray_wool.png","common":true},
  {"id":"light_gray_wool","name":"Light Gray Wool","hex":"#8e8e87","family":"color","category":"wool","texture":"light_gray_wool.png","common":true},
  {"id":"lime_carpet","name":"Lime Carpet","hex":"#70b91a","family":"color","category":"wool","texture":"lime_wool.png","common":true},
  {"id":"lime_wool","name":"Lime Wool","hex":"#70b91a","family":"color","category":"wool","texture":"lime_wool.png","common":true},
  {"id":"magenta_carpet","name":"Magenta Carpet","hex":"#be45b4","family":"color","category":"wool","texture":"magenta_wool.png","common":true},
  {"id":"magenta_wool","name":"Magenta Wool","hex":"#be45b4","family":"color","category":"wool","texture":"magenta_wool.png","common":true},
  {"id":"orange_carpet","name":"Orange Carpet","hex":"#f17614","family":"color","category":"wool","texture":"orange_wool.png","common":true},
  {"id":"orange_wool","name":"Orange Wool","hex":"#f17614","family":"color","category":"wool","texture":"orange_wool.png","common":true},
  {"id":"pink_carpet","name":"Pink Carpet","hex":"#ee8dac","family":"color","category":"wool","texture":"pink_wool.png","common":true},
  {"id":"pink_wool","name":"Pink Wool","hex":"#ee8dac","family":"color","category":"wool","texture":"pink_wool.png","common":true},
  {"id":"purple_carpet","name":"Purple Carpet","hex":"#7a2aad","family":"color","category":"wool","texture":"purple_wool.png","common":true},
  {"id":"purple_wool","name":"Purple Wool","hex":"#7a2aad","family":"color","category":"wool","texture":"purple_wool.png","common":true},
  {"id":"red_carpet","name":"Red Carpet","hex":"#a12723","family":"color","category":"wool","texture":"red_wool.png","common":true},
  {"id":"red_wool","name":"Red Wool","hex":"#a12723","family":"color","category":"wool","texture":"red_wool.png","common":true},
  {"id":"white_carpet","name":"White Carpet","hex":"#eaeced","family":"color","category":"wool","texture":"white_wool.png","common":true},
  {"id":"white_wool","name":"White Wool","hex":"#eaeced","family":"color","category":"wool","texture":"white_wool.png","common":true},
  {"id":"yellow_carpet","name":"Yellow Carpet","hex":"#f9c628","family":"color","category":"wool","texture":"yellow_wool.png","common":true},
  {"id":"yellow_wool","name":"Yellow Wool","hex":"#f9c628","family":"color","category":"wool","texture":"yellow_wool.png","common":true},
];
