import type { MinecraftBlockColor } from "./gradient-types";

// Representative top-face colors for common vanilla building blocks. Flat
// swatches keep this dataset reusable without shipping game texture assets.
export const MINECRAFT_BLOCK_COLORS: MinecraftBlockColor[] = [
  { id: "white_concrete", name: "White Concrete", hex: "#cfd5d6", family: "color", common: true },
  { id: "light_gray_concrete", name: "Light Gray Concrete", hex: "#7e7e76", family: "color", common: true },
  { id: "gray_concrete", name: "Gray Concrete", hex: "#36393d", family: "color", common: true },
  { id: "black_concrete", name: "Black Concrete", hex: "#080a0f", family: "color", common: true },
  { id: "brown_concrete", name: "Brown Concrete", hex: "#603b2b", family: "color", common: true },
  { id: "red_concrete", name: "Red Concrete", hex: "#8e2020", family: "color", common: true },
  { id: "orange_concrete", name: "Orange Concrete", hex: "#e06101", family: "color", common: true },
  { id: "yellow_concrete", name: "Yellow Concrete", hex: "#f0af15", family: "color", common: true },
  { id: "lime_concrete", name: "Lime Concrete", hex: "#5ea919", family: "color", common: true },
  { id: "green_concrete", name: "Green Concrete", hex: "#495b24", family: "color", common: true },
  { id: "cyan_concrete", name: "Cyan Concrete", hex: "#157788", family: "color", common: true },
  { id: "light_blue_concrete", name: "Light Blue Concrete", hex: "#2489c7", family: "color", common: true },
  { id: "blue_concrete", name: "Blue Concrete", hex: "#2c2e8f", family: "color", common: true },
  { id: "purple_concrete", name: "Purple Concrete", hex: "#64209c", family: "color", common: true },
  { id: "magenta_concrete", name: "Magenta Concrete", hex: "#a9309f", family: "color", common: true },
  { id: "pink_concrete", name: "Pink Concrete", hex: "#d6658f", family: "color", common: true },
  { id: "white_terracotta", name: "White Terracotta", hex: "#d1b2a1", family: "color", common: true },
  { id: "light_gray_terracotta", name: "Light Gray Terracotta", hex: "#876b62", family: "color", common: true },
  { id: "gray_terracotta", name: "Gray Terracotta", hex: "#392a24", family: "color", common: true },
  { id: "black_terracotta", name: "Black Terracotta", hex: "#251610", family: "color", common: true },
  { id: "brown_terracotta", name: "Brown Terracotta", hex: "#4d2f20", family: "color", common: true },
  { id: "red_terracotta", name: "Red Terracotta", hex: "#8f3d2f", family: "color", common: true },
  { id: "orange_terracotta", name: "Orange Terracotta", hex: "#a15325", family: "color", common: true },
  { id: "yellow_terracotta", name: "Yellow Terracotta", hex: "#ba8524", family: "color", common: true },
  { id: "lime_terracotta", name: "Lime Terracotta", hex: "#677535", family: "color", common: true },
  { id: "green_terracotta", name: "Green Terracotta", hex: "#4b522a", family: "color", common: true },
  { id: "cyan_terracotta", name: "Cyan Terracotta", hex: "#565b59", family: "color", common: true },
  { id: "light_blue_terracotta", name: "Light Blue Terracotta", hex: "#716c89", family: "color", common: true },
  { id: "blue_terracotta", name: "Blue Terracotta", hex: "#4a3b5b", family: "color", common: true },
  { id: "purple_terracotta", name: "Purple Terracotta", hex: "#764656", family: "color", common: true },
  { id: "magenta_terracotta", name: "Magenta Terracotta", hex: "#96576c", family: "color", common: true },
  { id: "pink_terracotta", name: "Pink Terracotta", hex: "#a24e4f", family: "color", common: true },
  { id: "quartz_block", name: "Quartz Block", hex: "#ece5d8", family: "stone", common: true },
  { id: "calcite", name: "Calcite", hex: "#dddcd2", family: "stone", common: true },
  { id: "smooth_sandstone", name: "Smooth Sandstone", hex: "#d8c58c", family: "stone", common: true },
  { id: "sandstone", name: "Sandstone", hex: "#d2bd7f", family: "stone", common: true },
  { id: "red_sandstone", name: "Red Sandstone", hex: "#b85d20", family: "stone", common: true },
  { id: "bricks", name: "Bricks", hex: "#966153", family: "stone", common: true },
  { id: "granite", name: "Granite", hex: "#956755", family: "stone", common: true },
  { id: "diorite", name: "Diorite", hex: "#b9b8b5", family: "stone", common: true },
  { id: "andesite", name: "Andesite", hex: "#888887", family: "stone", common: true },
  { id: "stone", name: "Stone", hex: "#7d7d7d", family: "stone", common: true },
  { id: "cobblestone", name: "Cobblestone", hex: "#70706f", family: "stone", common: true },
  { id: "tuff", name: "Tuff", hex: "#6d756d", family: "stone", common: true },
  { id: "deepslate", name: "Deepslate", hex: "#505052", family: "stone", common: true },
  { id: "blackstone", name: "Blackstone", hex: "#2d292f", family: "stone", common: true },
  { id: "basalt", name: "Basalt", hex: "#4f4c4f", family: "stone", common: true },
  { id: "obsidian", name: "Obsidian", hex: "#17121f", family: "stone", common: false },
  { id: "mud_bricks", name: "Mud Bricks", hex: "#876b57", family: "earth", common: true },
  { id: "packed_mud", name: "Packed Mud", hex: "#8c7457", family: "earth", common: true },
  { id: "dirt", name: "Dirt", hex: "#866043", family: "earth", common: true },
  { id: "coarse_dirt", name: "Coarse Dirt", hex: "#77533b", family: "earth", common: true },
  { id: "netherrack", name: "Netherrack", hex: "#6e3535", family: "earth", common: true },
  { id: "nether_bricks", name: "Nether Bricks", hex: "#2c1519", family: "earth", common: true },
  { id: "end_stone", name: "End Stone", hex: "#d8d89e", family: "earth", common: true },
  { id: "purpur_block", name: "Purpur Block", hex: "#a97ca8", family: "earth", common: true },
  { id: "oak_planks", name: "Oak Planks", hex: "#a98552", family: "wood", common: true },
  { id: "spruce_planks", name: "Spruce Planks", hex: "#73542f", family: "wood", common: true },
  { id: "birch_planks", name: "Birch Planks", hex: "#c7b77a", family: "wood", common: true },
  { id: "jungle_planks", name: "Jungle Planks", hex: "#a06b43", family: "wood", common: true },
  { id: "acacia_planks", name: "Acacia Planks", hex: "#ab5d37", family: "wood", common: true },
  { id: "dark_oak_planks", name: "Dark Oak Planks", hex: "#4a321d", family: "wood", common: true },
  { id: "mangrove_planks", name: "Mangrove Planks", hex: "#753630", family: "wood", common: true },
  { id: "cherry_planks", name: "Cherry Planks", hex: "#d79999", family: "wood", common: true },
  { id: "bamboo_planks", name: "Bamboo Planks", hex: "#c1a94a", family: "wood", common: true },
  { id: "crimson_planks", name: "Crimson Planks", hex: "#653147", family: "wood", common: true },
  { id: "warped_planks", name: "Warped Planks", hex: "#2b706c", family: "wood", common: true },
  { id: "prismarine", name: "Prismarine", hex: "#639c8f", family: "ocean", common: true },
  { id: "prismarine_bricks", name: "Prismarine Bricks", hex: "#63a294", family: "ocean", common: true },
  { id: "dark_prismarine", name: "Dark Prismarine", hex: "#315b4c", family: "ocean", common: true },
  { id: "sea_lantern", name: "Sea Lantern", hex: "#acd3c4", family: "ocean", common: false },
  { id: "oxidized_copper", name: "Oxidized Copper", hex: "#51a486", family: "metal", common: true },
  { id: "weathered_copper", name: "Weathered Copper", hex: "#6f8f72", family: "metal", common: true },
  { id: "exposed_copper", name: "Exposed Copper", hex: "#a66f54", family: "metal", common: true },
  { id: "copper_block", name: "Copper Block", hex: "#bd6a4a", family: "metal", common: true },
  { id: "iron_block", name: "Iron Block", hex: "#d8d8d8", family: "metal", common: false },
  { id: "gold_block", name: "Gold Block", hex: "#f7d43e", family: "metal", common: false },
  { id: "lapis_block", name: "Lapis Lazuli Block", hex: "#1e438c", family: "metal", common: false },
  { id: "emerald_block", name: "Emerald Block", hex: "#2acb57", family: "metal", common: false },
];
